// -----------------------------------------------------------------------
// <copyright file="SubscriptionConfirmationPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the SubscriptionConfirmationPage class
	/// </summary>
	public partial class SubscriptionConfirmationPage 
	{	
		public SubscriptionConfirmationPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets Message Label
		/// </summary> 
		private Label Message
		{
			get { return new Label("Message", "//p[text()='Thank you for subscribing to ']", 0, false); }
		}

		/// <summary>
		/// Gets SelctedStep Label
		/// </summary> 
		private Label SelctedStep
		{
			get { return new Label("SelctedStep", "//td[@class='selectedStep']", 0, false); }
		}

		/// <summary>
		/// Gets SubscribeStepTwoToolbar list
		/// </summary>
		public RequiredElements SubscribeStepTwoToolbar
		{
			get
			{
				return new RequiredElements
				{
					Name = "SubscribeStepTwoToolbar",
					Xpath = "//table[@class='progressbar']",
					Filter = "td",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Select Products"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","E-mail Address"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Details and Payment"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"class","selectedStep"},
								{"innerText","Confirmation"}
							}
						}
					}
				};
			}
		}

	}
}
	
