// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18408
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Spec.Homepage
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Footer")]
    [NUnit.Framework.CategoryAttribute("Footer")]
    public partial class FooterFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Footer.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Footer", "I want to be able to verify if footer is displayed.\r\nI want to be able to use eve" +
                    "ry footer link.", ProgrammingLanguage.CSharp, new string[] {
                        "Footer"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
testRunner.Given("I\'m on the Homepage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display footer")]
        [NUnit.Framework.CategoryAttribute("capacityconferences.com")]
        [NUnit.Framework.CategoryAttribute("euromoneytraining.com")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        [NUnit.Framework.CategoryAttribute("petroleumeconomist.com")]
        [NUnit.Framework.CategoryAttribute("managingip.com")]
        [NUnit.Framework.CategoryAttribute("capacitymagazine.com")]
        [NUnit.Framework.CategoryAttribute("euromoneyconferences.com")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        [NUnit.Framework.CategoryAttribute("globaltelecomsbusiness.com")]
        public virtual void Footer_ShouldDisplayFooter()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display footer", new string[] {
                        "capacityconferences.com",
                        "euromoneytraining.com",
                        "emergingmarkets.org",
                        "petroleumeconomist.com",
                        "managingip.com",
                        "capacitymagazine.com",
                        "euromoneyconferences.com",
                        "hedgefundintelligence.com",
                        "globaltelecomsbusiness.com"});
#line 12
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 13
testRunner.Then("the footer should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer -  Should display copyrights")]
        [NUnit.Framework.CategoryAttribute("capacityconferences.com")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        [NUnit.Framework.CategoryAttribute("petroleumeconomist.com")]
        [NUnit.Framework.CategoryAttribute("managingip.com")]
        [NUnit.Framework.CategoryAttribute("capacitymagazine.com")]
        [NUnit.Framework.CategoryAttribute("euromoneyconferences.com")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        [NUnit.Framework.CategoryAttribute("globaltelecomsbusiness.com")]
        public virtual void Footer_ShouldDisplayCopyrights()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer -  Should display copyrights", new string[] {
                        "capacityconferences.com",
                        "emergingmarkets.org",
                        "petroleumeconomist.com",
                        "managingip.com",
                        "capacitymagazine.com",
                        "euromoneyconferences.com",
                        "hedgefundintelligence.com",
                        "globaltelecomsbusiness.com"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 18
testRunner.Then("The Copyright should be displayed under the footer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display About Us page")]
        [NUnit.Framework.CategoryAttribute("euromoneytraining.com")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        [NUnit.Framework.CategoryAttribute("petroleumeconomist.com")]
        [NUnit.Framework.CategoryAttribute("managingip.com")]
        [NUnit.Framework.CategoryAttribute("euromoneyconferences.com")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        [NUnit.Framework.CategoryAttribute("globaltelecomsbusiness.com")]
        public virtual void Footer_ShouldDisplayAboutUsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display About Us page", new string[] {
                        "euromoneytraining.com",
                        "emergingmarkets.org",
                        "petroleumeconomist.com",
                        "managingip.com",
                        "euromoneyconferences.com",
                        "hedgefundintelligence.com",
                        "globaltelecomsbusiness.com"});
#line 22
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 23
testRunner.When("I enter About Us page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
testRunner.Then("About Us page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Contact Us page")]
        [NUnit.Framework.CategoryAttribute("euromoneytraining.com")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        [NUnit.Framework.CategoryAttribute("managingip.com")]
        [NUnit.Framework.CategoryAttribute("capacitymagazine.com")]
        [NUnit.Framework.CategoryAttribute("euromoneyconferences.com")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        [NUnit.Framework.CategoryAttribute("globaltelecomsbusiness.com")]
        public virtual void Footer_ShouldDisplayContactUsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Contact Us page", new string[] {
                        "euromoneytraining.com",
                        "emergingmarkets.org",
                        "managingip.com",
                        "capacitymagazine.com",
                        "euromoneyconferences.com",
                        "hedgefundintelligence.com",
                        "globaltelecomsbusiness.com"});
#line 28
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 29
testRunner.When("I enter Contact Us page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
testRunner.Then("Contact Us page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Sign-up page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        [NUnit.Framework.CategoryAttribute("managingip.com")]
        [NUnit.Framework.CategoryAttribute("capacitymagazine.com")]
        public virtual void Footer_ShouldDisplaySign_UpPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Sign-up page", new string[] {
                        "emergingmarkets.org",
                        "managingip.com",
                        "capacitymagazine.com"});
#line 33
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 34
testRunner.When("I enter Sign-up page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
testRunner.Then("Sign-up page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Subscribe page")]
        [NUnit.Framework.CategoryAttribute("petroleumeconomist.com")]
        public virtual void Footer_ShouldDisplaySubscribePage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Subscribe page", new string[] {
                        "petroleumeconomist.com"});
#line 38
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 39
testRunner.When("I enter Subscribe page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 40
testRunner.Then("Subscribe page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display NBO Subscribe page")]
        [NUnit.Framework.CategoryAttribute("managingip.com")]
        public virtual void Footer_ShouldDisplayNBOSubscribePage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display NBO Subscribe page", new string[] {
                        "managingip.com"});
#line 43
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 44
testRunner.When("I enter Subscribe page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
testRunner.Then("NBO Subscribe page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Feedback page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        public virtual void Footer_ShouldDisplayFeedbackPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Feedback page", new string[] {
                        "emergingmarkets.org"});
#line 48
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 49
testRunner.When("I enter Feedback page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
testRunner.Then("Feedback page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Terms and Conditions page")]
        [NUnit.Framework.CategoryAttribute("capacityconferences.com")]
        [NUnit.Framework.CategoryAttribute("euromoneytraining.com")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        [NUnit.Framework.CategoryAttribute("petroleumeconomist.com")]
        [NUnit.Framework.CategoryAttribute("capacitymagazine.com")]
        [NUnit.Framework.CategoryAttribute("euromoneyconferences.com")]
        public virtual void Footer_ShouldDisplayTermsAndConditionsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Terms and Conditions page", new string[] {
                        "capacityconferences.com",
                        "euromoneytraining.com",
                        "emergingmarkets.org",
                        "petroleumeconomist.com",
                        "capacitymagazine.com",
                        "euromoneyconferences.com"});
#line 54
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 55
testRunner.When("I enter Terms and Conditions page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
testRunner.Then("Terms and Conditions page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Privacy Policy page")]
        [NUnit.Framework.CategoryAttribute("capacityconferences.com")]
        [NUnit.Framework.CategoryAttribute("euromoneytraining.com")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        [NUnit.Framework.CategoryAttribute("petroleumeconomist.com")]
        [NUnit.Framework.CategoryAttribute("capacitymagazine.com")]
        [NUnit.Framework.CategoryAttribute("euromoneyconferences.com")]
        public virtual void Footer_ShouldDisplayPrivacyPolicyPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Privacy Policy page", new string[] {
                        "capacityconferences.com",
                        "euromoneytraining.com",
                        "emergingmarkets.org",
                        "petroleumeconomist.com",
                        "capacitymagazine.com",
                        "euromoneyconferences.com"});
#line 60
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 61
testRunner.When("I enter Privacy Policy page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 62
testRunner.Then("Privacy Policy page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display FAQs page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        [NUnit.Framework.CategoryAttribute("managingip.com")]
        [NUnit.Framework.CategoryAttribute("petroleumeconomist.com")]
        [NUnit.Framework.CategoryAttribute("euromoneyconferences.com")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void Footer_ShouldDisplayFAQsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display FAQs page", new string[] {
                        "emergingmarkets.org",
                        "managingip.com",
                        "petroleumeconomist.com",
                        "euromoneyconferences.com",
                        "hedgefundintelligence.com"});
#line 66
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 67
testRunner.When("I enter FAQs page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 68
testRunner.Then("FAQs page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Cookies page")]
        [NUnit.Framework.CategoryAttribute("capacityconferences.com")]
        [NUnit.Framework.CategoryAttribute("euromoneytraining.com")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        [NUnit.Framework.CategoryAttribute("managingip.com")]
        [NUnit.Framework.CategoryAttribute("petroleumeconomist.com")]
        [NUnit.Framework.CategoryAttribute("capacitymagazine.com")]
        [NUnit.Framework.CategoryAttribute("euromoneyconferences.com")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void Footer_ShouldDisplayCookiesPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Cookies page", new string[] {
                        "capacityconferences.com",
                        "euromoneytraining.com",
                        "emergingmarkets.org",
                        "managingip.com",
                        "petroleumeconomist.com",
                        "capacitymagazine.com",
                        "euromoneyconferences.com",
                        "hedgefundintelligence.com"});
#line 72
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 73
testRunner.When("I enter Cookies page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 74
testRunner.Then("Cookies page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Newspaper Archive page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        public virtual void Footer_ShouldDisplayNewspaperArchivePage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Newspaper Archive page", new string[] {
                        "emergingmarkets.org"});
#line 77
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 78
testRunner.When("I enter Newspaper Archive page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 79
testRunner.Then("Newspaper Archive page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Sponsored Reports page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        public virtual void Footer_ShouldDisplaySponsoredReportsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Sponsored Reports page", new string[] {
                        "emergingmarkets.org"});
#line 82
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 83
testRunner.When("I enter Sponsored Reports page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 84
testRunner.Then("Sponsored Reports page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Economics and Policy page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        public virtual void Footer_ShouldDisplayEconomicsAndPolicyPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Economics and Policy page", new string[] {
                        "emergingmarkets.org"});
#line 87
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 88
testRunner.Given("I\'m on the Homepage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 89
testRunner.When("I enter Economics and Policy page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 90
testRunner.Then("Economics and Policy page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Financial Markets page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        public virtual void Footer_ShouldDisplayFinancialMarketsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Financial Markets page", new string[] {
                        "emergingmarkets.org"});
#line 93
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 94
testRunner.When("I enter Financial Markets page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 95
testRunner.Then("Financial Markets page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Development page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        public virtual void Footer_ShouldDisplayDevelopmentPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Development page", new string[] {
                        "emergingmarkets.org"});
#line 98
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 99
testRunner.When("I enter Development page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 100
testRunner.Then("Development page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Middle East & Africa page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        public virtual void Footer_ShouldDisplayMiddleEastAfricaPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Middle East & Africa page", new string[] {
                        "emergingmarkets.org"});
#line 103
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 104
testRunner.When("I enter Middle East & Africa page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 105
testRunner.Then("Middle East & Africa page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Americas page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        public virtual void Footer_ShouldDisplayAmericasPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Americas page", new string[] {
                        "emergingmarkets.org"});
#line 109
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 110
testRunner.When("I enter Americas page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 111
testRunner.Then("Americas page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Asia page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        [NUnit.Framework.CategoryAttribute("euromoneyconferences.com")]
        public virtual void Footer_ShouldDisplayAsiaPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Asia page", new string[] {
                        "emergingmarkets.org",
                        "euromoneyconferences.com"});
#line 114
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 115
testRunner.When("I enter Asia page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 116
testRunner.Then("Asia page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Europe page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        [NUnit.Framework.CategoryAttribute("euromoneyconferences.com")]
        public virtual void Footer_ShouldDisplayEuropePage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Europe page", new string[] {
                        "emergingmarkets.org",
                        "euromoneyconferences.com"});
#line 119
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 120
testRunner.When("I enter Europe page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 121
testRunner.Then("Europe page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Polls And Awards page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        public virtual void Footer_ShouldDisplayPollsAndAwardsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Polls And Awards page", new string[] {
                        "emergingmarkets.org"});
#line 124
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 125
testRunner.When("I enter Polls And Awards page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 126
testRunner.Then("Polls And Awards page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Events page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        public virtual void Footer_ShouldDisplayEventsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Events page", new string[] {
                        "emergingmarkets.org"});
#line 129
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 130
testRunner.When("I enter Events page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 131
testRunner.Then("Events page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Comment And Opinion page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        public virtual void Footer_ShouldDisplayCommentAndOpinionPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Comment And Opinion page", new string[] {
                        "emergingmarkets.org"});
#line 134
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 135
testRunner.When("I enter Comment And Opinion page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 136
testRunner.Then("Comment And Opinion page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Features page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        public virtual void Footer_ShouldDisplayFeaturesPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Features page", new string[] {
                        "emergingmarkets.org"});
#line 139
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 140
testRunner.When("I enter Features page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 141
testRunner.Then("Features page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display News page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        public virtual void Footer_ShouldDisplayNewsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display News page", new string[] {
                        "emergingmarkets.org"});
#line 144
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 145
testRunner.When("I enter News page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 146
testRunner.Then("News page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display Research page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        public virtual void Footer_ShouldDisplayResearchPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display Research page", new string[] {
                        "emergingmarkets.org"});
#line 149
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 150
testRunner.When("I enter Research page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 151
testRunner.Then("Research page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display EM View page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        public virtual void Footer_ShouldDisplayEMViewPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display EM View page", new string[] {
                        "emergingmarkets.org"});
#line 154
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 155
testRunner.When("I enter EM View page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 156
testRunner.Then("EM View page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Footer - Should display RSS page")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        [NUnit.Framework.CategoryAttribute("managingip.com")]
        [NUnit.Framework.CategoryAttribute("petroleumeconomist.com")]
        [NUnit.Framework.CategoryAttribute("euromoneyconferences.com")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void Footer_ShouldDisplayRSSPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Footer - Should display RSS page", new string[] {
                        "emergingmarkets.org",
                        "managingip.com",
                        "petroleumeconomist.com",
                        "euromoneyconferences.com",
                        "hedgefundintelligence.com"});
#line 160
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 161
testRunner.When("I enter RSS page by footer link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 162
testRunner.Then("RSS page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
