// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18408
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Spec.Subscription
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Subscription")]
    [NUnit.Framework.CategoryAttribute("Subscription")]
    public partial class SubscriptionFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Subscription.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Subscription", "", ProgrammingLanguage.CSharp, new string[] {
                        "Subscription"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get EuroHedge subscription 1st package by credit card as " +
            "a new user with valid data provided")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetEuroHedgeSubscription1StPackageByCreditCardAsANewUserWithValidDataProvided()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get EuroHedge subscription 1st package by credit card as " +
                    "a new user with valid data provided", new string[] {
                        "hedgefundintelligence.com"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("I\'m on the Subscribe page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get EuroHedge subscription 2nd package by credit card as " +
            "a new user with valid data provided")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetEuroHedgeSubscription2NdPackageByCreditCardAsANewUserWithValidDataProvided()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get EuroHedge subscription 2nd package by credit card as " +
                    "a new user with valid data provided", new string[] {
                        "hedgefundintelligence.com"});
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
 testRunner.Given("I\'m on the Subscribe page and select 2nd package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 14
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get AsiaHedge subscription 1st package by credit card as " +
            "a new user with valid data provided")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetAsiaHedgeSubscription1StPackageByCreditCardAsANewUserWithValidDataProvided()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get AsiaHedge subscription 1st package by credit card as " +
                    "a new user with valid data provided", new string[] {
                        "hedgefundintelligence.com"});
#line 19
this.ScenarioSetup(scenarioInfo);
#line 20
 testRunner.Given("I\'m on the Asia Subscribe page and select 1st package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 21
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get AsiaHedge subscription 2nd package by credit card as " +
            "a new user with valid data provided")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetAsiaHedgeSubscription2NdPackageByCreditCardAsANewUserWithValidDataProvided()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get AsiaHedge subscription 2nd package by credit card as " +
                    "a new user with valid data provided", new string[] {
                        "hedgefundintelligence.com"});
#line 26
this.ScenarioSetup(scenarioInfo);
#line 27
 testRunner.Given("I\'m on the Asia Subscribe page and select 2nd package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 28
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get InvestHedge subscription 1st package by credit card a" +
            "s a new user with valid data provided")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetInvestHedgeSubscription1StPackageByCreditCardAsANewUserWithValidDataProvided()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get InvestHedge subscription 1st package by credit card a" +
                    "s a new user with valid data provided", new string[] {
                        "hedgefundintelligence.com"});
#line 33
this.ScenarioSetup(scenarioInfo);
#line 34
 testRunner.Given("I\'m on the InvestHedge page and select 1st package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 35
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 36
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get InvestHedge subscription 2nd package by credit card a" +
            "s a new user with valid data provided")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetInvestHedgeSubscription2NdPackageByCreditCardAsANewUserWithValidDataProvided()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get InvestHedge subscription 2nd package by credit card a" +
                    "s a new user with valid data provided", new string[] {
                        "hedgefundintelligence.com"});
#line 40
this.ScenarioSetup(scenarioInfo);
#line 41
 testRunner.Given("I\'m on the InvestHedge Subscribe page and select 2nd package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 42
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 43
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 44
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get AU subscription 1st package by credit card as a new u" +
            "ser with valid data provided")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetAUSubscription1StPackageByCreditCardAsANewUserWithValidDataProvided()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get AU subscription 1st package by credit card as a new u" +
                    "ser with valid data provided", new string[] {
                        "hedgefundintelligence.com"});
#line 48
this.ScenarioSetup(scenarioInfo);
#line 49
 testRunner.Given("I\'m on the AU Subscribe page and select 1st package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 50
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 51
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 52
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get AR subscription 1st package by credit card as a new u" +
            "ser with valid data provided")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetARSubscription1StPackageByCreditCardAsANewUserWithValidDataProvided()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get AR subscription 1st package by credit card as a new u" +
                    "ser with valid data provided", new string[] {
                        "hedgefundintelligence.com"});
#line 56
this.ScenarioSetup(scenarioInfo);
#line 57
 testRunner.Given("I\'m on the AR Subscribe page and select 1st package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 58
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 59
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get AR subscription 2nd package by credit card as a new u" +
            "ser with valid data provided")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetARSubscription2NdPackageByCreditCardAsANewUserWithValidDataProvided()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get AR subscription 2nd package by credit card as a new u" +
                    "ser with valid data provided", new string[] {
                        "hedgefundintelligence.com"});
#line 63
this.ScenarioSetup(scenarioInfo);
#line 64
 testRunner.Given("I\'m on the AR Subscribe page and select 2nd package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 65
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 66
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 67
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get EuroHedge subscription by credit card as a new user w" +
            "ith valid data provided")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetEuroHedgeSubscriptionByCreditCardAsANewUserWithValidDataProvided()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get EuroHedge subscription by credit card as a new user w" +
                    "ith valid data provided", new string[] {
                        "hedgefundintelligence.com"});
#line 70
this.ScenarioSetup(scenarioInfo);
#line 71
 testRunner.Given("I\'m on the EuroHedge Subscribe page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 72
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 73
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get AsiaHedge subscription by credit card as a new user w" +
            "ith valid data provided")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetAsiaHedgeSubscriptionByCreditCardAsANewUserWithValidDataProvided()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get AsiaHedge subscription by credit card as a new user w" +
                    "ith valid data provided", new string[] {
                        "hedgefundintelligence.com"});
#line 77
this.ScenarioSetup(scenarioInfo);
#line 78
 testRunner.Given("I\'m on the AsiaHedge Subscribe page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 79
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 80
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 81
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get AbsoluteUCITS subscription by credit card as a new us" +
            "er with valid data provided")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetAbsoluteUCITSSubscriptionByCreditCardAsANewUserWithValidDataProvided()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get AbsoluteUCITS subscription by credit card as a new us" +
                    "er with valid data provided", new string[] {
                        "hedgefundintelligence.com"});
#line 84
this.ScenarioSetup(scenarioInfo);
#line 85
 testRunner.Given("I\'m on the AbsoluteUCITS Subscribe page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 86
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 87
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get AbsoluteReturn subscription by credit card as a new u" +
            "ser with valid data provided")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetAbsoluteReturnSubscriptionByCreditCardAsANewUserWithValidDataProvided()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get AbsoluteReturn subscription by credit card as a new u" +
                    "ser with valid data provided", new string[] {
                        "hedgefundintelligence.com"});
#line 91
this.ScenarioSetup(scenarioInfo);
#line 92
 testRunner.Given("I\'m on the AbsoluteReturn Subscribe page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 93
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 94
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 95
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get InvestHedge subscription by credit card as a new user" +
            " with valid data provided")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetInvestHedgeSubscriptionByCreditCardAsANewUserWithValidDataProvided()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get InvestHedge subscription by credit card as a new user" +
                    " with valid data provided", new string[] {
                        "hedgefundintelligence.com"});
#line 98
this.ScenarioSetup(scenarioInfo);
#line 99
 testRunner.Given("I\'m on the InvestHedge Subscribe page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 100
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 101
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 102
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get AR subscription 1st package by credit card as a new u" +
            "ser with valid data provided All Fields Filled")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetARSubscription1StPackageByCreditCardAsANewUserWithValidDataProvidedAllFieldsFilled()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get AR subscription 1st package by credit card as a new u" +
                    "ser with valid data provided All Fields Filled", new string[] {
                        "hedgefundintelligence.com"});
#line 105
this.ScenarioSetup(scenarioInfo);
#line 106
 testRunner.Given("I\'m on the AR Subscribe page and select 1st package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 107
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided A" +
                    "ll Fields Filled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 108
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 109
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get AR subscription 2nd package by credit card as a new u" +
            "ser with valid data provided All Fields Filled")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetARSubscription2NdPackageByCreditCardAsANewUserWithValidDataProvidedAllFieldsFilled()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get AR subscription 2nd package by credit card as a new u" +
                    "ser with valid data provided All Fields Filled", new string[] {
                        "hedgefundintelligence.com"});
#line 112
this.ScenarioSetup(scenarioInfo);
#line 113
 testRunner.Given("I\'m on the AR Subscribe page and select 2nd package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 114
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided A" +
                    "ll Fields Filled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 115
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 116
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get AU subscription 1st package by credit card as a new u" +
            "ser with valid data provided All Fields Filled")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetAUSubscription1StPackageByCreditCardAsANewUserWithValidDataProvidedAllFieldsFilled()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get AU subscription 1st package by credit card as a new u" +
                    "ser with valid data provided All Fields Filled", new string[] {
                        "hedgefundintelligence.com"});
#line 119
this.ScenarioSetup(scenarioInfo);
#line 120
 testRunner.Given("I\'m on the AU Subscribe page and select 1st package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 121
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided A" +
                    "ll Fields Filled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 122
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 123
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get EuroHedge subscription 1st package by credit card as " +
            "a new user with valid data provided All Fields Filled")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetEuroHedgeSubscription1StPackageByCreditCardAsANewUserWithValidDataProvidedAllFieldsFilled()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get EuroHedge subscription 1st package by credit card as " +
                    "a new user with valid data provided All Fields Filled", new string[] {
                        "hedgefundintelligence.com"});
#line 126
this.ScenarioSetup(scenarioInfo);
#line 127
 testRunner.Given("I\'m on the Subscribe page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 128
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided A" +
                    "ll Fields Filled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 129
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 130
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get EuroHedge subscription 2nd package by credit card as " +
            "a new user with valid data provided All Fields Filled")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetEuroHedgeSubscription2NdPackageByCreditCardAsANewUserWithValidDataProvidedAllFieldsFilled()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get EuroHedge subscription 2nd package by credit card as " +
                    "a new user with valid data provided All Fields Filled", new string[] {
                        "hedgefundintelligence.com"});
#line 133
this.ScenarioSetup(scenarioInfo);
#line 134
 testRunner.Given("I\'m on the Subscribe page and select 2nd package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 135
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided A" +
                    "ll Fields Filled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 136
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 137
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get AsiaHedge subscription 1st package by credit card as " +
            "a new user with valid data provided All Fields Filled")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetAsiaHedgeSubscription1StPackageByCreditCardAsANewUserWithValidDataProvidedAllFieldsFilled()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get AsiaHedge subscription 1st package by credit card as " +
                    "a new user with valid data provided All Fields Filled", new string[] {
                        "hedgefundintelligence.com"});
#line 140
this.ScenarioSetup(scenarioInfo);
#line 141
 testRunner.Given("I\'m on the Asia Subscribe page and select 1st package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 142
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided A" +
                    "ll Fields Filled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 143
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 144
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get AsiaHedge subscription 2nd package by credit card as " +
            "a new user with valid data provided All Fields Filled")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetAsiaHedgeSubscription2NdPackageByCreditCardAsANewUserWithValidDataProvidedAllFieldsFilled()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get AsiaHedge subscription 2nd package by credit card as " +
                    "a new user with valid data provided All Fields Filled", new string[] {
                        "hedgefundintelligence.com"});
#line 147
this.ScenarioSetup(scenarioInfo);
#line 148
 testRunner.Given("I\'m on the Asia Subscribe page and select 2nd package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 149
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided A" +
                    "ll Fields Filled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 150
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 151
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get InvestHedge subscription 1st package by credit card a" +
            "s a new user with valid data provided All Fields Filled")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetInvestHedgeSubscription1StPackageByCreditCardAsANewUserWithValidDataProvidedAllFieldsFilled()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get InvestHedge subscription 1st package by credit card a" +
                    "s a new user with valid data provided All Fields Filled", new string[] {
                        "hedgefundintelligence.com"});
#line 154
this.ScenarioSetup(scenarioInfo);
#line 155
 testRunner.Given("I\'m on the InvestHedge page and select 1st package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 156
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided A" +
                    "ll Fields Filled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 157
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 158
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Should get InvestHedge subscription 2nd package by credit card a" +
            "s a new user with valid data provided All Fields Filled")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        public virtual void SubscribePage_ShouldGetInvestHedgeSubscription2NdPackageByCreditCardAsANewUserWithValidDataProvidedAllFieldsFilled()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Should get InvestHedge subscription 2nd package by credit card a" +
                    "s a new user with valid data provided All Fields Filled", new string[] {
                        "hedgefundintelligence.com"});
#line 161
this.ScenarioSetup(scenarioInfo);
#line 162
 testRunner.Given("I\'m on the InvestHedge Subscribe page and select 2nd package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 163
 testRunner.When("I try to get subscription by credit card as a new user with valid data provided A" +
                    "ll Fields Filled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 164
 testRunner.And("I fill all required data for credit card", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 165
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Subscribe page - Fill all fields and Fill billing address")]
        [NUnit.Framework.CategoryAttribute("hedgefundintelligence.com")]
        [NUnit.Framework.TestCaseAttribute("Credit Card", null)]
        [NUnit.Framework.TestCaseAttribute("Invoice", null)]
        public virtual void SubscribePage_FillAllFieldsAndFillBillingAddress(string paymentMeathod, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "hedgefundintelligence.com"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Subscribe page - Fill all fields and Fill billing address", @__tags);
#line 168
this.ScenarioSetup(scenarioInfo);
#line 169
 testRunner.Given("I\'m on the InvestHedge Subscribe page and select 2nd package", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 170
 testRunner.When("I fill all fields for user details and fill Billing Address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 171
 testRunner.And(string.Format("Select \"{0}\" and if it\'s sredit card I fill all required data for credit card", paymentMeathod), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 172
 testRunner.Then("I should get subscription as a new user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
