// -----------------------------------------------------------------------
// <copyright file="ViewYourSubscriptionsPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the ViewYourSubscriptionsPage class
	/// </summary>
	public partial class ViewYourSubscriptionsPage 
	{	
		public ViewYourSubscriptionsPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets ViewYourSubscriptionsRequiredElements list
		/// </summary>
		public RequiredElements ViewYourSubscriptionsRequiredElements
		{
			get
			{
				return new RequiredElements
				{
					Name = "ViewYourSubscriptionsRequiredElements",
					Xpath = "",
					Filter = "",
					Optional = false,
					List = new List<Element>
					{
						
					}
				};
			}
		}

	}
}
	
