
// -----------------------------------------------------------------------
// <copyright file="ApplicationConfiguration.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------

namespace Core.Configuration
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;

	/// <summary>
	/// Initializes a new instance of the ApplicationConfiguration class 
	/// </summary>
	public static class ApplicationConfiguration
	{
		/// <summary>
		/// Gets Browser value
		/// </summary>
		public static string Browser
		{
			get { return @"PhantomJS"; }
		}

		/// <summary>
		/// Gets Url value
		/// </summary>
		public static string Url
		{
			get { return @"http://qat.hedgefundintelligence.com/"; }
		}

		/// <summary>
		/// Gets TestDataKey value
		/// </summary>
		public static string TestDataKey
		{
			get { return @"hedgefundintelligence.com"; }
		}

		/// <summary>
		/// Gets LoginPageUrl value
		/// </summary>
		public static string LoginPageUrl
		{
			get { return @"Login.html"; }
		}

		/// <summary>
		/// Gets SearchResultsPageUrl value
		/// </summary>
		public static string SearchResultsPageUrl
		{
			get { return @"Search-Results.html"; }
		}

		/// <summary>
		/// Gets MyAccountPageUrl value
		/// </summary>
		public static string MyAccountPageUrl
		{
			get { return @"MyAccount.html"; }
		}

		/// <summary>
		/// Gets MyAccountChangePasswordUrl value
		/// </summary>
		public static string MyAccountChangePasswordUrl
		{
			get { return @"ChangePassword.html"; }
		}

		/// <summary>
		/// Gets MyAccountPasswordUpdatedUrl value
		/// </summary>
		public static string MyAccountPasswordUpdatedUrl
		{
			get { return @"ChangePassword.html"; }
		}

		/// <summary>
		/// Gets FreeTrialStepOneUrl value
		/// </summary>
		public static string FreeTrialStepOneUrl
		{
			get { return @"Subscribe.aspx?Config=FreeTrial"; }
		}

		/// <summary>
		/// Gets SubscribeStepOneUrl value
		/// </summary>
		public static string SubscribeStepOneUrl
		{
			get { return @"SubscribeNow"; }
		}

		/// <summary>
		/// Gets AboutUsUrl value
		/// </summary>
		public static string AboutUsUrl
		{
			get { return @"AboutUs.html"; }
		}

		/// <summary>
		/// Gets ContactUsUrl value
		/// </summary>
		public static string ContactUsUrl
		{
			get { return @"ContactUs.html"; }
		}

		/// <summary>
		/// Gets FeedbackUrl value
		/// </summary>
		public static string FeedbackUrl
		{
			get { return @"Feedback.html"; }
		}

		/// <summary>
		/// Gets TermsAndConditionsUrl value
		/// </summary>
		public static string TermsAndConditionsUrl
		{
			get { return @"TermsConditions.html"; }
		}

		/// <summary>
		/// Gets PrivacyPolicyUrl value
		/// </summary>
		public static string PrivacyPolicyUrl
		{
			get { return @"PrivacyPolicy.html"; }
		}

		/// <summary>
		/// Gets FAQUrl value
		/// </summary>
		public static string FAQUrl
		{
			get { return @"FAQ.html"; }
		}

		/// <summary>
		/// Gets SectorsUrl value
		/// </summary>
		public static string SectorsUrl
		{
			get { return @"Sectors/25194/Sectors.html"; }
		}

		/// <summary>
		/// Gets InterviewsUrl value
		/// </summary>
		public static string InterviewsUrl
		{
			get { return @"Interviews/25239/All-interviews.html"; }
		}

		/// <summary>
		/// Gets CFOsUrl value
		/// </summary>
		public static string CFOsUrl
		{
			get { return @"Stub/GTB-CFO.html"; }
		}

		/// <summary>
		/// Gets CMOsUrl value
		/// </summary>
		public static string CMOsUrl
		{
			get { return @"Stub/GTB-CMO.html"; }
		}

		/// <summary>
		/// Gets GTBTVUrl value
		/// </summary>
		public static string GTBTVUrl
		{
			get { return @"stub.aspx?stubid=23956"; }
		}

		/// <summary>
		/// Gets CookiesUrl value
		/// </summary>
		public static string CookiesUrl
		{
			get { return @"Cookies.html"; }
		}

		/// <summary>
		/// Gets NewspaperArchiveUrl value
		/// </summary>
		public static string NewspaperArchiveUrl
		{
			get { return @"Issue-Archive.html"; }
		}

		/// <summary>
		/// Gets SponsoredReportsUrl value
		/// </summary>
		public static string SponsoredReportsUrl
		{
			get { return @"Sponsored-Reports.html"; }
		}

		/// <summary>
		/// Gets EconomicsAndPolicyUrl value
		/// </summary>
		public static string EconomicsAndPolicyUrl
		{
			get { return @"Economics-and-Policy.html"; }
		}

		/// <summary>
		/// Gets FinancialMarketsUrl value
		/// </summary>
		public static string FinancialMarketsUrl
		{
			get { return @"Financial-Markets.html"; }
		}

		/// <summary>
		/// Gets DevelopmentUrl value
		/// </summary>
		public static string DevelopmentUrl
		{
			get { return @"Development.html"; }
		}

		/// <summary>
		/// Gets MiddleEastAndAfricaUrl value
		/// </summary>
		public static string MiddleEastAndAfricaUrl
		{
			get { return @"Middle-East-and-Africa.html"; }
		}

		/// <summary>
		/// Gets AmericasUrl value
		/// </summary>
		public static string AmericasUrl
		{
			get { return @"Americas.html"; }
		}

		/// <summary>
		/// Gets AsiaUrl value
		/// </summary>
		public static string AsiaUrl
		{
			get { return @"Asia.html"; }
		}

		/// <summary>
		/// Gets EuropeUrl value
		/// </summary>
		public static string EuropeUrl
		{
			get { return @"Europe.html"; }
		}

		/// <summary>
		/// Gets PollsAndAwardsUrl value
		/// </summary>
		public static string PollsAndAwardsUrl
		{
			get { return @"Polls-and-Awards.html"; }
		}

		/// <summary>
		/// Gets EventsUrl value
		/// </summary>
		public static string EventsUrl
		{
			get { return @"Forthcoming-Events.html"; }
		}

		/// <summary>
		/// Gets CommentAndOpinionUrl value
		/// </summary>
		public static string CommentAndOpinionUrl
		{
			get { return @"Comment-and-Opinion.html"; }
		}

		/// <summary>
		/// Gets FeaturesUrl value
		/// </summary>
		public static string FeaturesUrl
		{
			get { return @"Features.html"; }
		}

		/// <summary>
		/// Gets NewsUrl value
		/// </summary>
		public static string NewsUrl
		{
			get { return @"News.html"; }
		}

		/// <summary>
		/// Gets ResearchUrl value
		/// </summary>
		public static string ResearchUrl
		{
			get { return @"Research.html"; }
		}

		/// <summary>
		/// Gets EMViewUrl value
		/// </summary>
		public static string EMViewUrl
		{
			get { return @"EM-View.html"; }
		}

		/// <summary>
		/// Gets RSSUrl value
		/// </summary>
		public static string RSSUrl
		{
			get { return @"Rss-Feeds.html"; }
		}

		/// <summary>
		/// Gets AnalysisUrl value
		/// </summary>
		public static string AnalysisUrl
		{
			get { return @"Analysis.html"; }
		}

		/// <summary>
		/// Gets RegionsUrl value
		/// </summary>
		public static string RegionsUrl
		{
			get { return @"Regions.html"; }
		}

		/// <summary>
		/// Gets VideoUrl value
		/// </summary>
		public static string VideoUrl
		{
			get { return @"Video-Library.html"; }
		}

		/// <summary>
		/// Gets GlobalUrl value
		/// </summary>
		public static string GlobalUrl
		{
			get { return @"Global.html"; }
		}

		/// <summary>
		/// Gets NewsletterPreferencesUrl value
		/// </summary>
		public static string NewsletterPreferencesUrl
		{
			get { return @"EmailSettings.html"; }
		}

		/// <summary>
		/// Gets MyClippingsUrl value
		/// </summary>
		public static string MyClippingsUrl
		{
			get { return @"MyClippings.html"; }
		}

		/// <summary>
		/// Gets AdvancedSearchUrl value
		/// </summary>
		public static string AdvancedSearchUrl
		{
			get { return @"Advanced-Search"; }
		}

		/// <summary>
		/// Gets ImplicitlyWait value
		/// </summary>
		public static int ImplicitlyWait
		{
			get { return int.Parse("10"); }
		}
		
		/// <summary>
		/// Gets WaitBeforeComparingRequiredElements value
		/// </summary>
		public static int WaitBeforeComparingRequiredElements
		{
			get { return int.Parse("10"); }
		}
		
		/// <summary>
		/// Gets StaleExceptionTiemout value
		/// </summary>
		public static int StaleExceptionTiemout
		{
			get { return int.Parse("2000"); }
		}
		
		/// <summary>
		/// Gets ShortTimeout value
		/// </summary>
		public static int ShortTimeout
		{
			get { return int.Parse("2000"); }
		}
		
		/// <summary>
		/// Gets MediumTimeout value
		/// </summary>
		public static int MediumTimeout
		{
			get { return int.Parse("10000"); }
		}
		
		/// <summary>
		/// Gets LongTimeout value
		/// </summary>
		public static int LongTimeout
		{
			get { return int.Parse("30000"); }
		}
		
		/// <summary>
		/// Gets WaitForSuccessTimeout value
		/// </summary>
		public static int WaitForSuccessTimeout
		{
			get { return int.Parse("200"); }
		}
		
		/// <summary>
		/// Gets CultureInfo value
		/// </summary>
		public static string CultureInfo
		{
			get { return @"en-GB"; }
		}

		/// <summary>
		/// Gets LogFileName value
		/// </summary>
		public static string LogFileName
		{
			get { return @"TestRun.log"; }
		}

		/// <summary>
		/// Gets ScreenShotsFolder value
		/// </summary>
		public static string ScreenShotsFolder
		{
			get { return @"FailedTestsScreens"; }
		}

		/// <summary>
		/// Gets TestsConfigFilePath value
		/// </summary>
		public static string TestsConfigFilePath
		{
			get { return @"TestsConfiguration.xml"; }
		}

		/// <summary>
		/// Gets ExistingUserName value
		/// </summary>
		public static string ExistingUserName
		{
			get { return @"adavidson@euromoneyplc.com"; }
		}

		/// <summary>
		/// Gets ExistingUserPassword value
		/// </summary>
		public static string ExistingUserPassword
		{
			get { return @"pointer"; }
		}

		/// <summary>
		/// Gets ExistingExpiredUserName value
		/// </summary>
		public static string ExistingExpiredUserName
		{
			get { return @"cscs@sdf.ui"; }
		}

		/// <summary>
		/// Gets ExistingExpiredUserPassword value
		/// </summary>
		public static string ExistingExpiredUserPassword
		{
			get { return @"cc12848"; }
		}

		/// <summary>
		/// Gets ChangePasswordTestExistingUserName value
		/// </summary>
		public static string ChangePasswordTestExistingUserName
		{
			get { return @"frameworkTestsEmail@te.st"; }
		}

		/// <summary>
		/// Gets ChangePasswordTestExistingUserPassword value
		/// </summary>
		public static string ChangePasswordTestExistingUserPassword
		{
			get { return @"fpg20922"; }
		}

		/// <summary>
		/// Gets ChangePasswordTestDifferentUserPassword value
		/// </summary>
		public static string ChangePasswordTestDifferentUserPassword
		{
			get { return @"different_fpg20922"; }
		}

		/// <summary>
		/// Gets IncorrectUserName value
		/// </summary>
		public static string IncorrectUserName
		{
			get { return @"false_fp_em_user@euromoneyplc.test"; }
		}

		/// <summary>
		/// Gets IncorrectUserPassword value
		/// </summary>
		public static string IncorrectUserPassword
		{
			get { return @"false_fpg20922"; }
		}

		/// <summary>
		/// Gets NotExistingUserName value
		/// </summary>
		public static string NotExistingUserName
		{
			get { return @"02042014_emorg@te.st"; }
		}

		/// <summary>
		/// Gets NotExistingPassword value
		/// </summary>
		public static string NotExistingPassword
		{
			get { return @"jjhhgg656565@"; }
		}

		/// <summary>
		/// Gets GetAllElementsSuffix value
		/// </summary>
		public static string GetAllElementsSuffix
		{
			get { return @"//*"; }
		}

		/// <summary>
		/// Gets RandomEmailSuffix value
		/// </summary>
		public static string RandomEmailSuffix
		{
			get { return @"@te.st"; }
		}

		/// <summary>
		/// Gets CommentTestText value
		/// </summary>
		public static string CommentTestText
		{
			get { return @"Comment."; }
		}

		/// <summary>
		/// Gets FaqTopMenuComponent value
		/// </summary>
		public static string FaqTopMenuComponent
		{
			get { return @"Default"; }
		}

		/// <summary>
		/// Gets CookiesTopMenuComponent value
		/// </summary>
		public static string CookiesTopMenuComponent
		{
			get { return @"Cookies"; }
		}

		/// <summary>
		/// Gets MailtrapMailboxNumber value
		/// </summary>
		public static string MailtrapMailboxNumber
		{
			get { return @"15106"; }
		}

		/// <summary>
		/// Gets MailtrapToken value
		/// </summary>
		public static string MailtrapToken
		{
			get { return @"bbaed6b2da700f33f0f42dcdac7ec7f7"; }
		}

		/// <summary>
		/// Gets PasswordRetrieveRegex value
		/// </summary>
		public static string PasswordRetrieveRegex
		{
			get { return @"Password:.{4,9}"; }
		}

		/// <summary>
		/// Gets PasswordRetrieveFromEmailPrefix value
		/// </summary>
		public static string PasswordRetrieveFromEmailPrefix
		{
			get { return @"Password: "; }
		}

		/// <summary>
		/// Gets PasswordRetrieveFromEmailSufix value
		/// </summary>
		public static string PasswordRetrieveFromEmailSufix
		{
			get { return @"<"; }
		}

		/// <summary>
		/// Gets ZeroFreeTrialPage value
		/// </summary>
		public static bool ZeroFreeTrialPage
		{
			get { return bool.Parse("true"); }
		}

		/// <summary>
		/// Gets RegistrationType value
		/// </summary>
		public static string RegistrationType
		{
			get { return @"FreeTrial"; }
		}

		/// <summary>
		/// Gets SubscribtionZeroPage value
		/// </summary>
		public static bool SubscribtionZeroPage
		{
			get { return bool.Parse("true"); }
		}

		/// <summary>
		/// Gets CreditCardType value
		/// </summary>
		public static string CreditCardType
		{
			get { return @"MasterCard"; }
		}

		/// <summary>
		/// Gets CreditCardNumber value
		/// </summary>
		public static string CreditCardNumber
		{
			get { return @"5555555555554444"; }
		}

		/// <summary>
		/// Gets CreditCardExpirationMonth value
		/// </summary>
		public static string CreditCardExpirationMonth
		{
			get { return @"02"; }
		}

		/// <summary>
		/// Gets CreditCardExpirationYear value
		/// </summary>
		public static string CreditCardExpirationYear
		{
			get { return @"2016"; }
		}

		/// <summary>
		/// Gets CreditCardCVN value
		/// </summary>
		public static string CreditCardCVN
		{
			get { return @"123"; }
		}

		/// <summary>
		/// Gets CreditCardTypeVisa value
		/// </summary>
		public static string CreditCardTypeVisa
		{
			get { return @"Visa"; }
		}

		/// <summary>
		/// Gets CreditCardNumberVisa value
		/// </summary>
		public static string CreditCardNumberVisa
		{
			get { return @"4024007146519862"; }
		}

		/// <summary>
		/// Gets ConsumerId value
		/// </summary>
		public static int ConsumerId
		{
			get { return int.Parse("168"); }
		}
		
		/// <summary>
		/// Gets ConsumerPassword value
		/// </summary>
		public static string ConsumerPassword
		{
			get { return @""; }
		}

	}
}
