// -----------------------------------------------------------------------
// <copyright file="CMOsPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the CMOsPage class
	/// </summary>
	public partial class CMOsPage 
	{	
		public CMOsPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets CMOs Label
		/// </summary> 
		private Label CMOs
		{
			get { return new Label("CMOs", "//h2//span[contains(text(), 'GTB for chief marketing officers')]", 0, false); }
		}

	}
}
	
