// -----------------------------------------------------------------------
// <copyright file="CFOsPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the CFOsPage class
	/// </summary>
	public partial class CFOsPage 
	{	
		public CFOsPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets CFOs Label
		/// </summary> 
		private Label CFOs
		{
			get { return new Label("CFOs", "//h2//span[contains(text(), 'GTB for chief financial officers')]", 0, false); }
		}

	}
}
	
