// -----------------------------------------------------------------------
// <copyright file="SubscribeNBOCheckoutStepOnePage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the SubscribeNBOCheckoutStepOnePage class
	/// </summary>
	public partial class SubscribeNBOCheckoutStepOnePage 
	{	
		public SubscribeNBOCheckoutStepOnePage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets SubscribeNBOCheckoutStepOneRegistrationPanel list
		/// </summary>
		public RequiredElements SubscribeNBOCheckoutStepOneRegistrationPanel
		{
			get
			{
				return new RequiredElements
				{
					Name = "SubscribeNBOCheckoutStepOneRegistrationPanel",
					Xpath = "//div[@class='steps']",
					Filter = "p|span|h2|h3|h4|h5",
					Optional = true,
					List = new List<Element>
					{
						new Element
						{
							Name = "h2",
							Type = "h2",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Managing Intellectual Property"}
							}
						}, new Element
						{
							Name = "p",
							Type = "p",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "p",
							Type = "p",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Managing IP covers all aspects of IP law and practice, focusing on the business and practical issues of importance to IP owners.Online resources include regularly updated news and reports; interviews; surveys; in-depth features; special reports; and data. Coverage spans patents, trade marks, copyright, domain names and other areas of intellectual property."}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Managing IP covers all aspects of IP law and practice, focusing on the business and practical issues of importance to IP owners."}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Online resources include regularly updated news and reports; interviews; surveys; in-depth features; special reports; and data. Coverage spans patents, trade marks, copyright, domain names and other areas of intellectual property."}
							}
						}, new Element
						{
							Name = "p",
							Type = "p",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "h3",
							Type = "h3",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Subscribe to Managing Intellectual Property"}
							}
						}, new Element
						{
							Name = "h4",
							Type = "h4",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","12 Months"}
							}
						}, new Element
						{
							Name = "h5",
							Type = "h5",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","£1500.00"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"id","ctl00_MainContent_baseProduct_SubscriptionProduct_SubscriptionsRepeater_ctl00_spanTick"}
							}
						}, new Element
						{
							Name = "h4",
							Type = "h4",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","24 Months"}
							}
						}, new Element
						{
							Name = "h5",
							Type = "h5",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","£2700.00"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Saving of 10%:                                                £300.00"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"id","ctl00_MainContent_baseProduct_SubscriptionProduct_SubscriptionsRepeater_ctl01_spanTick"}
							}
						}, new Element
						{
							Name = "h4",
							Type = "h4",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","36 Months"}
							}
						}, new Element
						{
							Name = "h5",
							Type = "h5",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","£3825.00"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Saving of 15%:                                                £675.00"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"id","ctl00_MainContent_baseProduct_SubscriptionProduct_SubscriptionsRepeater_ctl02_spanTick"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"id","mySelectText0"},
								{"innerText","1"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","£1500.00"}
							}
						}, new Element
						{
							Name = "p",
							Type = "p",
							Attributes = new Dictionary<string, string>
							{
								{"id","ctl00_MainContent_baseProduct_TaxSection"},
								{"innerText","Tax (if applicable) will be added later"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets SubscribeNBOCheckoutStepOneToolbar list
		/// </summary>
		public RequiredElements SubscribeNBOCheckoutStepOneToolbar
		{
			get
			{
				return new RequiredElements
				{
					Name = "SubscribeNBOCheckoutStepOneToolbar",
					Xpath = "//div[@class='toolbar']",
					Filter = "span|img|input",
					Optional = true,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"id","ctl00_HeaderModule_lblProduct"},
								{"innerText","Choose Term"}
							}
						}, new Element
						{
							Name = "img",
							Type = "Image",
							Attributes = new Dictionary<string, string>
							{
								{"src","/SITE_BUILDER_FILES/assets/images/site/active.gif"},
								{"alt","Choose Term: you are here"},
								{"id","ctl00_HeaderModule_step1Image"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"id","ctl00_HeaderModule_lblDetails"},
								{"innerText","Your Details"}
							}
						}, new Element
						{
							Name = "img",
							Type = "Image",
							Attributes = new Dictionary<string, string>
							{
								{"src","/SITE_BUILDER_FILES/assets/images/site/default.gif"},
								{"alt","Your Details"},
								{"id","ctl00_HeaderModule_step2Image"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"id","ctl00_HeaderModule_lblPayment"},
								{"innerText","Payment"}
							}
						}, new Element
						{
							Name = "img",
							Type = "Image",
							Attributes = new Dictionary<string, string>
							{
								{"src","/SITE_BUILDER_FILES/assets/images/site/default.gif"},
								{"alt","Payment"},
								{"id","ctl00_HeaderModule_step3Image"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"id","ctl00_HeaderModule_lblConfirmation"},
								{"innerText","Confirmation"}
							}
						}, new Element
						{
							Name = "img",
							Type = "Image",
							Attributes = new Dictionary<string, string>
							{
								{"src","/SITE_BUILDER_FILES/assets/images/site/default.gif"},
								{"alt","Confirmation"},
								{"id","ctl00_HeaderModule_step4Image"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"id","ctl00_HeaderModule_UserStatusCtrl_lblCurrency"},
								{"innerText","UK (£)"}
							}
						}, new Element
						{
							Name = "input",
							Type = "Button",
							Attributes = new Dictionary<string, string>
							{
								{"value","Change Region"},
								{"id","ctl00_HeaderModule_UserStatusCtrl_lnkCountry"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","United Kingdom (GBP)"}
							}
						}, new Element
						{
							Name = "input",
							Type = "radio",
							Attributes = new Dictionary<string, string>
							{
								{"checked","checked"},
								{"value","chkGBP"},
								{"id","ctl00_HeaderModule_UserStatusCtrl_chkGBP"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Rest of Europe (EUR)"}
							}
						}, new Element
						{
							Name = "input",
							Type = "radio",
							Attributes = new Dictionary<string, string>
							{
								{"value","chkEUR"},
								{"id","ctl00_HeaderModule_UserStatusCtrl_chkEUR"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Rest of World (USD)"}
							}
						}, new Element
						{
							Name = "input",
							Type = "radio",
							Attributes = new Dictionary<string, string>
							{
								{"value","chkUSD"},
								{"id","ctl00_HeaderModule_UserStatusCtrl_chkUSD"}
							}
						}, new Element
						{
							Name = "input",
							Type = "Button",
							Attributes = new Dictionary<string, string>
							{
								{"value","close"},
								{"id","ctl00_HeaderModule_UserStatusCtrl_lnkCloseCountry"}
							}
						}, new Element
						{
							Name = "input",
							Type = "Button",
							Attributes = new Dictionary<string, string>
							{
								{"value","X"},
								{"id","ctl00_HeaderModule_UserStatusCtrl_lnkCloseX"}
							}
						}, new Element
						{
							Name = "input",
							Type = "Button",
							Attributes = new Dictionary<string, string>
							{
								{"value","Live Chat"},
								{"id","ctl00_HeaderModule_UserStatusCtrl_btnShowLiveChat"}
							}
						}, new Element
						{
							Name = "input",
							Type = "Button",
							Attributes = new Dictionary<string, string>
							{
								{"value","X"},
								{"id","ctl00_HeaderModule_UserStatusCtrl_btnCloseLiveChat"}
							}
						}, new Element
						{
							Name = "img",
							Type = "Image",
							Attributes = new Dictionary<string, string>
							{
								{"src","http://image.providesupport.com/image/acname/online-208149153.gif"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets SubscribeNBOCheckoutStepOneFooterLinks list
		/// </summary>
		public RequiredElements SubscribeNBOCheckoutStepOneFooterLinks
		{
			get
			{
				return new RequiredElements
				{
					Name = "SubscribeNBOCheckoutStepOneFooterLinks",
					Xpath = "//div[@id='footerlinks']",
					Filter = "a",
					Optional = true,
					List = new List<Element>
					{
						new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/About-Us.html"},
								{"id","ctl00_FooterModule_lnkFAQ"},
								{"innerText","FAQs"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Privacy.html"},
								{"id","ctl00_FooterModule_lnkPrivacy"},
								{"innerText","Privacy Policy"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Terms.html"},
								{"id","ctl00_FooterModule_lnkTcs"},
								{"innerText","Terms & Conditions"}
							}
						}
					}
				};
			}
		}

	}
}
	
