// -----------------------------------------------------------------------
// <copyright file="SignUpSuccessfulPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the SignUpSuccessfulPage class
	/// </summary>
	public partial class SignUpSuccessfulPage 
	{	
		public SignUpSuccessfulPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets SuccessfulMessage Label
		/// </summary> 
		private Label SuccessfulMessage
		{
			get { return new Label("SuccessfulMessage", "//p[contains(text(), 'Thank you for setting up your online account for Euromoney Conferences.')]", 0, false); }
		}

		/// <summary>
		/// Gets Header HeaderComponent
		/// </summary> 
		public HeaderComponent Header
		{
			get { return new HeaderComponent(); }
		}

	}
}
	
