// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18408
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Spec.MyAccount
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Newsletter preferences")]
    [NUnit.Framework.CategoryAttribute("NewsletterPreferences")]
    public partial class NewsletterPreferencesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "NewsletterPreferences.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Newsletter preferences", "I want to be able to change my newsletter preferences.", ProgrammingLanguage.CSharp, new string[] {
                        "NewsletterPreferences"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
#line 6
 testRunner.Given("I\'m on the Newsletter Preferences page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("My account - Should Sign Up for News Alerts")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        [NUnit.Framework.CategoryAttribute("capacitymagazine.com")]
        public virtual void MyAccount_ShouldSignUpForNewsAlerts()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My account - Should Sign Up for News Alerts", new string[] {
                        "emergingmarkets.org",
                        "capacitymagazine.com"});
#line 9
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 10
 testRunner.When("I sign up for News Alerts Newsletter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then("Update successful message should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
 testRunner.When("I go back to newsletter preferences", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
 testRunner.Then("Newsletter sign up is saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("My account - Should Sign Out from News Alerts")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        [NUnit.Framework.CategoryAttribute("capacitymagazine.com")]
        public virtual void MyAccount_ShouldSignOutFromNewsAlerts()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My account - Should Sign Out from News Alerts", new string[] {
                        "emergingmarkets.org",
                        "capacitymagazine.com"});
#line 16
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 17
 testRunner.When("I sign up for News Alerts Newsletter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
 testRunner.Then("Newsletter sign up is saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 19
 testRunner.When("I sign out from News Alerts Newsletter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
 testRunner.Then("Newsletter sign out is saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("My account - Should Choose Html version of email format")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        [NUnit.Framework.CategoryAttribute("petroleumeconomist.com")]
        [NUnit.Framework.CategoryAttribute("capacitymagazine.com")]
        public virtual void MyAccount_ShouldChooseHtmlVersionOfEmailFormat()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My account - Should Choose Html version of email format", new string[] {
                        "emergingmarkets.org",
                        "petroleumeconomist.com",
                        "capacitymagazine.com"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 24
 testRunner.When("I sign up for News Alerts Newsletter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 25
 testRunner.And("I choose Html version of email format and save", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.Then("Html version of email format is saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("My account - Should Choose Text version of email format")]
        [NUnit.Framework.CategoryAttribute("emergingmarkets.org")]
        [NUnit.Framework.CategoryAttribute("petroleumeconomist.com")]
        [NUnit.Framework.CategoryAttribute("capacitymagazine.com")]
        public virtual void MyAccount_ShouldChooseTextVersionOfEmailFormat()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My account - Should Choose Text version of email format", new string[] {
                        "emergingmarkets.org",
                        "petroleumeconomist.com",
                        "capacitymagazine.com"});
#line 29
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 30
 testRunner.When("I sign up for News Alerts Newsletter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 31
 testRunner.And("I choose Text version of email format and save", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.Then("Text version of email format is saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("My account - Should Sign Up for Petroleum Economist Monthly Magazine Update")]
        [NUnit.Framework.CategoryAttribute("petroleumeconomist.com")]
        public virtual void MyAccount_ShouldSignUpForPetroleumEconomistMonthlyMagazineUpdate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My account - Should Sign Up for Petroleum Economist Monthly Magazine Update", new string[] {
                        "petroleumeconomist.com"});
#line 35
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 36
 testRunner.When("I sign up for Petroleum Economist Monthly Magazine Update Newsletter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 37
 testRunner.Then("Monthly Magazine Update Newsletter sign up is saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("My account - Should Sign Up for Petroleum Economist Breaking News")]
        [NUnit.Framework.CategoryAttribute("petroleumeconomist.com")]
        public virtual void MyAccount_ShouldSignUpForPetroleumEconomistBreakingNews()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My account - Should Sign Up for Petroleum Economist Breaking News", new string[] {
                        "petroleumeconomist.com"});
#line 40
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 41
 testRunner.When("I sign up for Petroleum Economist Breaking News Newsletter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 42
 testRunner.Then("Breaking News Newsletter sign up is saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("My account - Should Sign Up for Petroleum Economist Blog Email")]
        [NUnit.Framework.CategoryAttribute("petroleumeconomist.com")]
        public virtual void MyAccount_ShouldSignUpForPetroleumEconomistBlogEmail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My account - Should Sign Up for Petroleum Economist Blog Email", new string[] {
                        "petroleumeconomist.com"});
#line 45
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 46
 testRunner.When("I sign up for Petroleum Economist Blog Email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 47
 testRunner.Then("Blog Email sign up is saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("My account - Should Sign Out from Petroleum Economist Monthly Magazine Update")]
        [NUnit.Framework.CategoryAttribute("petroleumeconomist.com")]
        public virtual void MyAccount_ShouldSignOutFromPetroleumEconomistMonthlyMagazineUpdate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My account - Should Sign Out from Petroleum Economist Monthly Magazine Update", new string[] {
                        "petroleumeconomist.com"});
#line 50
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 51
 testRunner.When("I sign out from Petroleum Economist Monthly Magazine Update Newsletter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
 testRunner.Then("Monthly Magazine Update Newsletter sign out is saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("My account - Should Sign Out from Petroleum Economist Breaking News")]
        [NUnit.Framework.CategoryAttribute("petroleumeconomist.com")]
        public virtual void MyAccount_ShouldSignOutFromPetroleumEconomistBreakingNews()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My account - Should Sign Out from Petroleum Economist Breaking News", new string[] {
                        "petroleumeconomist.com"});
#line 55
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 56
 testRunner.When("I sign out from Petroleum Economist Breaking News Newsletter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 57
 testRunner.Then("Breaking News Newsletter sign out is saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("My account Should Sign Out from Petroleum Economist Blog Email")]
        [NUnit.Framework.CategoryAttribute("petroleumeconomist.com")]
        public virtual void MyAccountShouldSignOutFromPetroleumEconomistBlogEmail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("My account Should Sign Out from Petroleum Economist Blog Email", new string[] {
                        "petroleumeconomist.com"});
#line 60
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 61
 testRunner.When("I sign out from Petroleum Economist Blog Email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 62
 testRunner.Then("Blog Email sign out is saved", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
