// -----------------------------------------------------------------------
// <copyright file="AboutUsPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the AboutUsPage class
	/// </summary>
	public partial class AboutUsPage 
	{	
		public AboutUsPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets AboutUs Label
		/// </summary> 
		private Label AboutUs
		{
			get { return new Label("AboutUs", "//span[text()='About Us']", 0, false); }
		}

		/// <summary>
		/// Gets Header HeaderComponent
		/// </summary> 
		public HeaderComponent Header
		{
			get { return new HeaderComponent(); }
		}

		/// <summary>
		/// Gets Footer FooterComponent
		/// </summary> 
		public FooterComponent Footer
		{
			get { return new FooterComponent(); }
		}

		/// <summary>
		/// Gets SidePanel SidePanelComponent
		/// </summary> 
		public SidePanelComponent SidePanel
		{
			get { return new SidePanelComponent(); }
		}

		/// <summary>
		/// Gets TopMenu TopMenuComponent
		/// </summary> 
		public TopMenuComponent TopMenu
		{
			get { return new TopMenuComponent(); }
		}

		/// <summary>
		/// Gets Breadcrumb BreadcrumbComponent
		/// </summary> 
		public BreadcrumbComponent Breadcrumb
		{
			get { return new BreadcrumbComponent(); }
		}

		/// <summary>
		/// Gets AboutUsRequiredElementsList list
		/// </summary>
		public RequiredElements AboutUsRequiredElementsList
		{
			get
			{
				return new RequiredElements
				{
					Name = "AboutUsRequiredElementsList",
					Xpath = "//div[@class='normal']",
					Filter = "b",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","OVERVIEW"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","NEWS AND ANALYSIS"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","DATA"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","EVENTS"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","EDITORIAL STAFF BIOS"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","(See Contact Us for full staff contact information)"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Absolute Return"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Josh Friedlander"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Editor"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Simone FoxmanStaff Writer"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Absolute UCITS"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","AsiaHedge"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Aradhna Dayal"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Editor"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Rodney Diola Deputy Editor"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","EuroHedge"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Nick Evans Editor"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Rob Murray"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Associate Editor"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Hugh Leask Senior Reporter"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","InvestHedge"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Niki Natarajan Editor"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Susan Barreto"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Deputy Editor"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Kristen Schultheiss"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Reporter"}
							}
						}
					}
				};
			}
		}

	}
}
	
