// -----------------------------------------------------------------------
// <copyright file="AddressSelectionPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the AddressSelectionPage class
	/// </summary>
	public partial class AddressSelectionPage 
	{	
		public AddressSelectionPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets ProceedToPayment Button
		/// </summary> 
		private Button ProceedToPayment
		{
			get { return new Button("ProceedToPayment", "//input[contains(@id, 'btnProceed')]", 0, false); }
		}

	}
}
	
