// -----------------------------------------------------------------------
// <copyright file="AdvancedSearchPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the AdvancedSearchPage class
	/// </summary>
	public partial class AdvancedSearchPage 
	{	
		public AdvancedSearchPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets Header HeaderComponent
		/// </summary> 
		public HeaderComponent Header
		{
			get { return new HeaderComponent(); }
		}

		/// <summary>
		/// Gets Footer FooterComponent
		/// </summary> 
		public FooterComponent Footer
		{
			get { return new FooterComponent(); }
		}

		/// <summary>
		/// Gets SidePanel SidePanelComponent
		/// </summary> 
		public SidePanelComponent SidePanel
		{
			get { return new SidePanelComponent(); }
		}

		/// <summary>
		/// Gets TopMenu TopMenuComponent
		/// </summary> 
		public TopMenuComponent TopMenu
		{
			get { return new TopMenuComponent(); }
		}

		/// <summary>
		/// Gets AdvancedSearchPageRequiredElements list
		/// </summary>
		public RequiredElements AdvancedSearchPageRequiredElements
		{
			get
			{
				return new RequiredElements
				{
					Name = "AdvancedSearchPageRequiredElements",
					Xpath = "//section",
					Filter = "label|input|select",
					Optional = false,
					List = new List<Element>
					{
						
					}
				};
			}
		}

	}
}
	
