// -----------------------------------------------------------------------
// <copyright file="ArticlePage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the ArticlePage class
	/// </summary>
	public partial class ArticlePage 
	{	
		public ArticlePage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets AddComment Button
		/// </summary> 
		private Button AddComment
		{
			get { return new Button("AddComment", "//a[text()='Add Comment']", 0, false); }
		}

		/// <summary>
		/// Gets AddCommentConfirmationMessage Label
		/// </summary> 
		private Label AddCommentConfirmationMessage
		{
			get { return new Label("AddCommentConfirmationMessage", "//span[text()='Thank you for  your comments. Subject to approval, they will be published on the site  shortly.']", 0, false); }
		}

		/// <summary>
		/// Gets Print Link
		/// </summary> 
		private Link Print
		{
			get { return new Link("Print", "//a[text()='Print Article']", 0, false); }
		}

		/// <summary>
		/// Gets AddToMyClippings Link
		/// </summary> 
		private Link AddToMyClippings
		{
			get { return new Link("AddToMyClippings", "//a[text()= 'Add clipping']", 0, false); }
		}

		/// <summary>
		/// Gets YourName Textbox
		/// </summary> 
		private Textbox YourName
		{
			get { return new Textbox("YourName", "//input[@id=//label[text()='Your name (required)']/@for]", 0, false); }
		}

		/// <summary>
		/// Gets YourEmail Textbox
		/// </summary> 
		private Textbox YourEmail
		{
			get { return new Textbox("YourEmail", "//input[@id=//label[text()='Your email address (required)']/@for]", 0, false); }
		}

		/// <summary>
		/// Gets YourComments Textbox
		/// </summary> 
		private Textbox YourComments
		{
			get { return new Textbox("YourComments", "//textarea[@id=//label[text()='Your comments (required)']/@for]", 0, false); }
		}

		/// <summary>
		/// Gets Captcha Textbox
		/// </summary> 
		private Textbox Captcha
		{
			get { return new Textbox("Captcha", "//input[contains(@id, 'recaptcha') and @type='text']", 0, true); }
		}

		/// <summary>
		/// Gets Submit Button
		/// </summary> 
		private Button Submit
		{
			get { return new Button("Submit", "//input[@value='Submit']", 0, false); }
		}

		/// <summary>
		/// Gets ArticleTitle Label
		/// </summary> 
		private Label ArticleTitle
		{
			get { return new Label("ArticleTitle", "//h1[span/text()]", 0, false); }
		}

		/// <summary>
		/// Gets Header HeaderComponent
		/// </summary> 
		public HeaderComponent Header
		{
			get { return new HeaderComponent(); }
		}

		/// <summary>
		/// Gets Footer FooterComponent
		/// </summary> 
		public FooterComponent Footer
		{
			get { return new FooterComponent(); }
		}

		/// <summary>
		/// Gets SidePanel SidePanelComponent
		/// </summary> 
		public SidePanelComponent SidePanel
		{
			get { return new SidePanelComponent(); }
		}

		/// <summary>
		/// Gets TopMenu TopMenuComponent
		/// </summary> 
		public TopMenuComponent TopMenu
		{
			get { return new TopMenuComponent(); }
		}

		/// <summary>
		/// Gets Breadcrumb BreadcrumbComponent
		/// </summary> 
		public BreadcrumbComponent Breadcrumb
		{
			get { return new BreadcrumbComponent(); }
		}

	}
}
	
