// -----------------------------------------------------------------------
// <copyright file="BreadcrumbComponent.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the BreadcrumbComponent class
	/// </summary>
	public partial class BreadcrumbComponent 
	{	
		public BreadcrumbComponent(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets AboutUsBreadcrumb list
		/// </summary>
		public RequiredElements AboutUsBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "AboutUsBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText",">>"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","About Us"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets ContactUsBreadcrumb list
		/// </summary>
		public RequiredElements ContactUsBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "ContactUsBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText",">>"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","About Us"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","AboutUs.html"},
								{"innerText","About Us"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText",">>"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Contact Us"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets FeedbackBreadcrumb list
		/// </summary>
		public RequiredElements FeedbackBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "FeedbackBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Feedback"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets TermsBreadcrumb list
		/// </summary>
		public RequiredElements TermsBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "TermsBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Terms"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets PrivacyBreadcrumb list
		/// </summary>
		public RequiredElements PrivacyBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "PrivacyBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Privacy"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets FAQBreadcrumb list
		/// </summary>
		public RequiredElements FAQBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "FAQBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText",">>"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","About Us"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","AboutUs.html"},
								{"innerText","About Us"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText",">>"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","FAQ"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets CookiesBreadcrumb list
		/// </summary>
		public RequiredElements CookiesBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "CookiesBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText",">>"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","About Us"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","AboutUs.html"},
								{"innerText","About Us"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText",">>"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Cookies"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets NewspaperArchiveBreadcrumb list
		/// </summary>
		public RequiredElements NewspaperArchiveBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "NewspaperArchiveBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Issue Archive"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets SponsoredReportsBreadcrumb list
		/// </summary>
		public RequiredElements SponsoredReportsBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "SponsoredReportsBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Sponsored Reports"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets EconomicsAndPolicyBreadcrumb list
		/// </summary>
		public RequiredElements EconomicsAndPolicyBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "EconomicsAndPolicyBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Economics & Policy"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets FinancialMarketsBreadcrumb list
		/// </summary>
		public RequiredElements FinancialMarketsBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "FinancialMarketsBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Financial Markets"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets DevelopmentBreadcrumb list
		/// </summary>
		public RequiredElements DevelopmentBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "DevelopmentBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Development"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets MiddleEastAndAfricaBreadcrumb list
		/// </summary>
		public RequiredElements MiddleEastAndAfricaBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "MiddleEastAndAfricaBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Regions"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","Regions.html"},
								{"innerText","Regions"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Middle East & Africa"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets AmericasBreadcrumb list
		/// </summary>
		public RequiredElements AmericasBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "AmericasBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Regions"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","Regions.html"},
								{"innerText","Regions"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Americas"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets AsiaBreadcrumb list
		/// </summary>
		public RequiredElements AsiaBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "AsiaBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Regions"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","Regions.html"},
								{"innerText","Regions"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Asia"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets EmergingEuropeBreadcrumb list
		/// </summary>
		public RequiredElements EmergingEuropeBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "EmergingEuropeBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Regions"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","Regions.html"},
								{"innerText","Regions"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Europe"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets PollsAndAwardsBreadcrumb list
		/// </summary>
		public RequiredElements PollsAndAwardsBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "PollsAndAwardsBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Polls and Awards"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets EventsBreadcrumb list
		/// </summary>
		public RequiredElements EventsBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "EventsBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText",">>"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Forthcoming Events"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets CommentAndOpinionBreadcrumb list
		/// </summary>
		public RequiredElements CommentAndOpinionBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "CommentAndOpinionBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Comment & Opinion"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets FeaturesBreadcrumb list
		/// </summary>
		public RequiredElements FeaturesBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "FeaturesBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Features"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets NewsBreadcrumb list
		/// </summary>
		public RequiredElements NewsBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "NewsBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText",">>"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","News"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets ResearchBreadcrumb list
		/// </summary>
		public RequiredElements ResearchBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "ResearchBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Research"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets EMViewBreadcrumb list
		/// </summary>
		public RequiredElements EMViewBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "EMViewBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","EM View"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets RSSFeedsBreadcrumb list
		/// </summary>
		public RequiredElements RSSFeedsBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "RSSFeedsBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText",">>"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","RSS Feeds"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets LoginBreadcrumb list
		/// </summary>
		public RequiredElements LoginBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "LoginBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Login"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets AnalysisBreadcrumb list
		/// </summary>
		public RequiredElements AnalysisBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "AnalysisBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Analysis"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets RegionsBreadcrumb list
		/// </summary>
		public RequiredElements RegionsBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "RegionsBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Regions"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets VideoBreadcrumb list
		/// </summary>
		public RequiredElements VideoBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "VideoBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Video Library"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets GlobalBreadcrumb list
		/// </summary>
		public RequiredElements GlobalBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "GlobalBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Regions"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","Regions.html"},
								{"innerText","Regions"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Global"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets MyAccountBreadcrumb list
		/// </summary>
		public RequiredElements MyAccountBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "MyAccountBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","My Account"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets MyAccountChangePasswordBreadcrumb list
		/// </summary>
		public RequiredElements MyAccountChangePasswordBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "MyAccountChangePasswordBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText",">>"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","My Account"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","MyAccount.html"},
								{"innerText","My Account"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText",">>"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Change Password"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets MyAccountPasswordUpdatedBreadcrumb list
		/// </summary>
		public RequiredElements MyAccountPasswordUpdatedBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "MyAccountPasswordUpdatedBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText",">>"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","My Account"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","MyAccount.html"},
								{"innerText","My Account"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText",">>"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Change Password"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets MyAccountNewsletterPreferencesBreadcrumb list
		/// </summary>
		public RequiredElements MyAccountNewsletterPreferencesBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "MyAccountNewsletterPreferencesBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","My Account"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","My-Account.html"},
								{"innerText","My Account"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Email Preferences"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets MyAccountMyClippingsBreadcrumb list
		/// </summary>
		public RequiredElements MyAccountMyClippingsBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "MyAccountMyClippingsBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","My Account"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","My-Account.html"},
								{"innerText","My Account"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","My Clippings"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets SearchResultsBreadcrumb list
		/// </summary>
		public RequiredElements SearchResultsBreadcrumb
		{
			get
			{
				return new RequiredElements
				{
					Name = "SearchResultsBreadcrumb",
					Xpath = "//div[@class='breadcrumb']",
					Filter = "span|a",
					Optional = true,
					List = new List<Element>
					{
						new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","./"},
								{"innerText","Home"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","::"}
							}
						}, new Element
						{
							Name = "span",
							Type = "span",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Search Results"}
							}
						}
					}
				};
			}
		}

	}
}
	
