// -----------------------------------------------------------------------
// <copyright file="ChangePasswordPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the ChangePasswordPage class
	/// </summary>
	public partial class ChangePasswordPage 
	{	
		public ChangePasswordPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets ChangePasswordHeader Label
		/// </summary> 
		private Label ChangePasswordHeader
		{
			get { return new Label("ChangePasswordHeader", "//h1[text()='Change password']", 0, false); }
		}

		/// <summary>
		/// Gets Submit Button
		/// </summary> 
		private Button Submit
		{
			get { return new Button("Submit", "//p[@class='submit_buttons']//input[contains(@name, 'btnSubmit')]", 0, false); }
		}

		/// <summary>
		/// Gets OldPassword Textbox
		/// </summary> 
		public Textbox OldPassword
		{
			get { return new Textbox("OldPassword", "//input[contains(@name, 'OldPassword')]", 0, false); }
		}

		/// <summary>
		/// Gets NewPassword Textbox
		/// </summary> 
		public Textbox NewPassword
		{
			get { return new Textbox("NewPassword", "//input[contains(@name, 'txtNewPassword')]", 0, false); }
		}

		/// <summary>
		/// Gets ConfirmNewPassword Textbox
		/// </summary> 
		public Textbox ConfirmNewPassword
		{
			get { return new Textbox("ConfirmNewPassword", "//input[contains(@name, 'ConfirmNewPassword')]", 0, false); }
		}

		/// <summary>
		/// Gets MissingOldPasswordValidationMessage Label
		/// </summary> 
		private Label MissingOldPasswordValidationMessage
		{
			get { return new Label("MissingOldPasswordValidationMessage", "//span[text()='Please enter your old password']", 0, false); }
		}

		/// <summary>
		/// Gets MissingNewPasswordValidationMessage Label
		/// </summary> 
		private Label MissingNewPasswordValidationMessage
		{
			get { return new Label("MissingNewPasswordValidationMessage", "//span[text()='Please enter your new password']", 0, false); }
		}

		/// <summary>
		/// Gets MissingConfirmNewPasswordValidationMessage Label
		/// </summary> 
		private Label MissingConfirmNewPasswordValidationMessage
		{
			get { return new Label("MissingConfirmNewPasswordValidationMessage", "//span[text()='Please confirm your new password']", 0, false); }
		}

		/// <summary>
		/// Gets PasswordDoNotMatchValidationMessage Label
		/// </summary> 
		private Label PasswordDoNotMatchValidationMessage
		{
			get { return new Label("PasswordDoNotMatchValidationMessage", "//span[text()='The details you have provided are invalid. Please re-enter and try again. ']", 3, false); }
		}

		/// <summary>
		/// Gets YourNewPasswordDoNotMatchValidationMessage Label
		/// </summary> 
		private Label YourNewPasswordDoNotMatchValidationMessage
		{
			get { return new Label("YourNewPasswordDoNotMatchValidationMessage", "//span[text()='Your new passwords do not match']", 3, false); }
		}

		/// <summary>
		/// Gets YourPasswordHasBeenUpdated Label
		/// </summary> 
		private Label YourPasswordHasBeenUpdated
		{
			get { return new Label("YourPasswordHasBeenUpdated", "//div[@class='normal']//span[text()='Password Updated']", 3, false); }
		}

		/// <summary>
		/// Gets Header HeaderComponent
		/// </summary> 
		public HeaderComponent Header
		{
			get { return new HeaderComponent(); }
		}

		/// <summary>
		/// Gets Footer FooterComponent
		/// </summary> 
		public FooterComponent Footer
		{
			get { return new FooterComponent(); }
		}

		/// <summary>
		/// Gets SidePanel SidePanelComponent
		/// </summary> 
		public SidePanelComponent SidePanel
		{
			get { return new SidePanelComponent(); }
		}

		/// <summary>
		/// Gets TopMenu TopMenuComponent
		/// </summary> 
		public TopMenuComponent TopMenu
		{
			get { return new TopMenuComponent(); }
		}

		/// <summary>
		/// Gets Breadcrumb BreadcrumbComponent
		/// </summary> 
		public BreadcrumbComponent Breadcrumb
		{
			get { return new BreadcrumbComponent(); }
		}

		/// <summary>
		/// Gets ChangePasswordPageRequiredElements list
		/// </summary>
		public RequiredElements ChangePasswordPageRequiredElements
		{
			get
			{
				return new RequiredElements
				{
					Name = "ChangePasswordPageRequiredElements",
					Xpath = "//div[contains(@id,'Form')]",
					Filter = "label|input",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "label",
							Type = "label",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Old Password"}
							}
						}, new Element
						{
							Name = "input",
							Type = "TextBox",
							Attributes = new Dictionary<string, string>
							{
								{"id","ctl00_phMain_txtOldPassword"}
							}
						}, new Element
						{
							Name = "label",
							Type = "label",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","New Password"}
							}
						}, new Element
						{
							Name = "input",
							Type = "TextBox",
							Attributes = new Dictionary<string, string>
							{
								{"id","ctl00_phMain_txtNewPassword"}
							}
						}, new Element
						{
							Name = "label",
							Type = "label",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Confirm new password"}
							}
						}, new Element
						{
							Name = "input",
							Type = "TextBox",
							Attributes = new Dictionary<string, string>
							{
								{"id","ctl00_phMain_txtConfirmNewPassword"}
							}
						}, new Element
						{
							Name = "input",
							Type = "Button",
							Attributes = new Dictionary<string, string>
							{
								{"value","Submit"},
								{"id","ctl00_phMain_btnSubmit"}
							}
						}
					}
				};
			}
		}

	}
}
	
