// -----------------------------------------------------------------------
// <copyright file="ConfirmTermsPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the ConfirmTermsPage class
	/// </summary>
	public partial class ConfirmTermsPage 
	{	
		public ConfirmTermsPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets PrivacyPolicy Checkbox
		/// </summary> 
		private Checkbox PrivacyPolicy
		{
			get { return new Checkbox("PrivacyPolicy", "//input[contains(@name, 'privacypolicy')]", 0, false); }
		}

		/// <summary>
		/// Gets TermsAndConditions Checkbox
		/// </summary> 
		private Checkbox TermsAndConditions
		{
			get { return new Checkbox("TermsAndConditions", "//input[contains(@name, 'termsconditions')]", 0, false); }
		}

		/// <summary>
		/// Gets Continue Button
		/// </summary> 
		private Button Continue
		{
			get { return new Button("Continue", "//input[@value='Continue']", 0, false); }
		}

	}
}
	
