// -----------------------------------------------------------------------
// <copyright file="ContactUsPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the ContactUsPage class
	/// </summary>
	public partial class ContactUsPage 
	{	
		public ContactUsPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets ContactUs Label
		/// </summary> 
		private Label ContactUs
		{
			get { return new Label("ContactUs", "//span[text()='Contact Us']", 0, false); }
		}

		/// <summary>
		/// Gets Header HeaderComponent
		/// </summary> 
		public HeaderComponent Header
		{
			get { return new HeaderComponent(); }
		}

		/// <summary>
		/// Gets Footer FooterComponent
		/// </summary> 
		public FooterComponent Footer
		{
			get { return new FooterComponent(); }
		}

		/// <summary>
		/// Gets SidePanel SidePanelComponent
		/// </summary> 
		public SidePanelComponent SidePanel
		{
			get { return new SidePanelComponent(); }
		}

		/// <summary>
		/// Gets TopMenu TopMenuComponent
		/// </summary> 
		public TopMenuComponent TopMenu
		{
			get { return new TopMenuComponent(); }
		}

		/// <summary>
		/// Gets Breadcrumb BreadcrumbComponent
		/// </summary> 
		public BreadcrumbComponent Breadcrumb
		{
			get { return new BreadcrumbComponent(); }
		}

		/// <summary>
		/// Gets ContactUsRequiredElementsList list
		/// </summary>
		public RequiredElements ContactUsRequiredElementsList
		{
			get
			{
				return new RequiredElements
				{
					Name = "ContactUsRequiredElementsList",
					Xpath = "//div[@class='normal']",
					Filter = "b",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Editorial & Data Contacts"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","HedgeFund Intelligence"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Absolute Return"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Absolute UCITS"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","AsiaHedge"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","EuroHedge"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","InvestHedge"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Advertising"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Americas and Europe"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Asia"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Events"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Subscriptions Sales"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Americas"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Europe"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Asia"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Offices"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","London"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","New York"}
							}
						}, new Element
						{
							Name = "b",
							Type = "b",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Hong Kong"}
							}
						}
					}
				};
			}
		}

	}
}
	
