// -----------------------------------------------------------------------
// <copyright file="EventsPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the EventsPage class
	/// </summary>
	public partial class EventsPage 
	{	
		public EventsPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets Events Label
		/// </summary> 
		private Label Events
		{
			get { return new Label("Events", "//a[text()= 'Forthcoming Events']", 0, false); }
		}

		/// <summary>
		/// Gets InvestHedgeForum2014 Link
		/// </summary> 
		public Link InvestHedgeForum2014
		{
			get { return new Link("InvestHedgeForum2014", "//a[text()='InvestHedge Forum 2014']", 0, false); }
		}

		/// <summary>
		/// Gets Header HeaderComponent
		/// </summary> 
		public HeaderComponent Header
		{
			get { return new HeaderComponent(); }
		}

		/// <summary>
		/// Gets Footer FooterComponent
		/// </summary> 
		public FooterComponent Footer
		{
			get { return new FooterComponent(); }
		}

		/// <summary>
		/// Gets SidePanel SidePanelComponent
		/// </summary> 
		public SidePanelComponent SidePanel
		{
			get { return new SidePanelComponent(); }
		}

		/// <summary>
		/// Gets TopMenu TopMenuComponent
		/// </summary> 
		public TopMenuComponent TopMenu
		{
			get { return new TopMenuComponent(); }
		}

		/// <summary>
		/// Gets Breadcrumb BreadcrumbComponent
		/// </summary> 
		public BreadcrumbComponent Breadcrumb
		{
			get { return new BreadcrumbComponent(); }
		}

	}
}
	
