// -----------------------------------------------------------------------
// <copyright file="FooterComponent.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the FooterComponent class
	/// </summary>
	public partial class FooterComponent 
	{	
		public FooterComponent(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets AboutUs Link
		/// </summary> 
		private Link AboutUs
		{
			get { return new Link("AboutUs", "//div[@class='footer_box']//a[text()='About Us']", 0, false); }
		}

		/// <summary>
		/// Gets ContactUs Link
		/// </summary> 
		private Link ContactUs
		{
			get { return new Link("ContactUs", "//div[@class='footer_box']//a[text()='Contact Us']", 0, false); }
		}

		/// <summary>
		/// Gets SignUp Link
		/// </summary> 
		private Link SignUp
		{
			get { return new Link("SignUp", "//a[text()='Sign-up']", 0, false); }
		}

		/// <summary>
		/// Gets Subscribe Link
		/// </summary> 
		private Link Subscribe
		{
			get { return new Link("Subscribe", "//div[@class='footer_box']//a[text()='Subscribe']", 0, false); }
		}

		/// <summary>
		/// Gets Feedback Link
		/// </summary> 
		private Link Feedback
		{
			get { return new Link("Feedback", "//a[text()='Feedback']", 0, false); }
		}

		/// <summary>
		/// Gets TermsAndConditions Link
		/// </summary> 
		private Link TermsAndConditions
		{
			get { return new Link("TermsAndConditions", "//a[text()='Terms & Conditions']", 0, false); }
		}

		/// <summary>
		/// Gets PrivacyPolicy Link
		/// </summary> 
		private Link PrivacyPolicy
		{
			get { return new Link("PrivacyPolicy", "//a[text()='Privacy Policy']", 0, false); }
		}

		/// <summary>
		/// Gets FAQ Link
		/// </summary> 
		private Link FAQ
		{
			get { return new Link("FAQ", "//a[@href='/FAQ.html']", 0, false); }
		}

		/// <summary>
		/// Gets Cookies Link
		/// </summary> 
		private Link Cookies
		{
			get { return new Link("Cookies", "//span[text()='Updated']", 0, false); }
		}

		/// <summary>
		/// Gets NewspaperArchive Link
		/// </summary> 
		private Link NewspaperArchive
		{
			get { return new Link("NewspaperArchive", "//a[text()='Newspaper Archive']", 0, false); }
		}

		/// <summary>
		/// Gets SponsoredReports Link
		/// </summary> 
		private Link SponsoredReports
		{
			get { return new Link("SponsoredReports", "//a[text()='Sponsored Reports']", 0, false); }
		}

		/// <summary>
		/// Gets EconomicsPolicy Link
		/// </summary> 
		private Link EconomicsPolicy
		{
			get { return new Link("EconomicsPolicy", "//a[text()='Economics & Policy']", 0, false); }
		}

		/// <summary>
		/// Gets FinancialMarkets Link
		/// </summary> 
		private Link FinancialMarkets
		{
			get { return new Link("FinancialMarkets", "//a[text()='Financial Markets']", 0, false); }
		}

		/// <summary>
		/// Gets Development Link
		/// </summary> 
		private Link Development
		{
			get { return new Link("Development", "//a[text()='Development']", 0, false); }
		}

		/// <summary>
		/// Gets MiddleEastAfrica Link
		/// </summary> 
		private Link MiddleEastAfrica
		{
			get { return new Link("MiddleEastAfrica", "//div[@id='footer']//a[text()='Middle East & Africa']", 0, false); }
		}

		/// <summary>
		/// Gets Americas Link
		/// </summary> 
		private Link Americas
		{
			get { return new Link("Americas", "//div[@id='footer']//a[text()='Americas']", 3, false); }
		}

		/// <summary>
		/// Gets Asia Link
		/// </summary> 
		private Link Asia
		{
			get { return new Link("Asia", "//div[@id='footer']//a[text()='Asia']", 0, false); }
		}

		/// <summary>
		/// Gets Europe Link
		/// </summary> 
		private Link Europe
		{
			get { return new Link("Europe", "//a[text()='Europe']", 0, false); }
		}

		/// <summary>
		/// Gets PollsAndAwards Link
		/// </summary> 
		private Link PollsAndAwards
		{
			get { return new Link("PollsAndAwards", "//a[text()='Polls & Awards']", 0, false); }
		}

		/// <summary>
		/// Gets Events Link
		/// </summary> 
		private Link Events
		{
			get { return new Link("Events", "//a[text()='HFI Events']", 0, false); }
		}

		/// <summary>
		/// Gets CommentAndOpinion Link
		/// </summary> 
		private Link CommentAndOpinion
		{
			get { return new Link("CommentAndOpinion", "//div[@id='footer']//a[text()='Comment & Opinion']", 0, false); }
		}

		/// <summary>
		/// Gets Features Link
		/// </summary> 
		private Link Features
		{
			get { return new Link("Features", "//div[@id='footer']//a[text()='Features']", 0, false); }
		}

		/// <summary>
		/// Gets News Link
		/// </summary> 
		private Link News
		{
			get { return new Link("News", "//div[@id='footer']//a[text()='News']", 0, false); }
		}

		/// <summary>
		/// Gets Research Link
		/// </summary> 
		private Link Research
		{
			get { return new Link("Research", "//a[text()='Research']", 0, false); }
		}

		/// <summary>
		/// Gets EMView Link
		/// </summary> 
		private Link EMView
		{
			get { return new Link("EMView", "//a[text()='EM View']", 0, false); }
		}

		/// <summary>
		/// Gets RSS Link
		/// </summary> 
		private Link RSS
		{
			get { return new Link("RSS", "//a[text()='RSS Feeds']", 0, false); }
		}

		/// <summary>
		/// Gets Copyright Label
		/// </summary> 
		private Label Copyright
		{
			get { return new Label("Copyright", "//p[contains(text(), 'Copyright')]", 0, false); }
		}

		/// <summary>
		/// Gets FooterComponentRequiredElements list
		/// </summary>
		public RequiredElements FooterComponentRequiredElements
		{
			get
			{
				return new RequiredElements
				{
					Name = "FooterComponentRequiredElements",
					Xpath = "//div[@class='footer_box']",
					Filter = "a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","javascript:{};"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","javascript:{};"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","javascript:{};"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href",""},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl01_link"},
								{"innerText","About HFI"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/AboutUs.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl01_rptSubMenu_ctl01_link"},
								{"innerText","About Us"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/ContactUs.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl01_rptSubMenu_ctl02_link"},
								{"innerText","Contact Us"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/SubscribeNow.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl01_rptSubMenu_ctl03_link"},
								{"innerText","Subscribe"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/FreeTrial.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl01_rptSubMenu_ctl04_link"},
								{"innerText","Free Trial"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/FAQ.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl01_rptSubMenu_ctl05_link"},
								{"innerText","FAQ's"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Press-Room.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl01_rptSubMenu_ctl06_link"},
								{"innerText","Press Room"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/TermsConditions.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl01_rptSubMenu_ctl07_link"},
								{"innerText","Terms & Conditions"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Cookies.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl01_rptSubMenu_ctl08_link"},
								{"innerText","Cookies Updated"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/PrivacyPolicy.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl01_rptSubMenu_ctl09_link"},
								{"innerText","Privacy Policy"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Sitemap.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl01_rptSubMenu_ctl10_link"},
								{"innerText","Sitemap"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Stub.aspx?StubID=22745"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl01_rptSubMenu_ctl11_link"},
								{"innerText","Help & Support"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href",""},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl02_link"},
								{"innerText","Resources"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Special-Reports.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl02_rptSubMenu_ctl01_link"},
								{"innerText","Special Reports"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","http://data.hedgefundintelligence.com/funds4/"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl02_rptSubMenu_ctl02_link"},
								{"innerText","Database"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Database-Global-Indices-Performance.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl02_rptSubMenu_ctl03_link"},
								{"innerText","Indices"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Performance-Global-Briefing.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl02_rptSubMenu_ctl04_link"},
								{"innerText","Global Briefing"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Forthcoming-Events.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl02_rptSubMenu_ctl05_link"},
								{"innerText","HFI Events"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Reprints.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl02_rptSubMenu_ctl06_link"},
								{"innerText","Reprints"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","http://data.hedgefundintelligence.com/funds4/directory/255/default.aspx"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl02_rptSubMenu_ctl07_link"},
								{"innerText","Directory"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","http://www.hedgefundintelligence.com/fund-quick-links"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl02_rptSubMenu_ctl08_link"},
								{"innerText","Fund Quick Links"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href",""},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl03_link"},
								{"innerText","My HFI"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/EmailSettings.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl03_rptSubMenu_ctl01_link"},
								{"innerText","Email Preferences"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/MyClippings.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl03_rptSubMenu_ctl02_link"},
								{"innerText","My clippings"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/MySavedSearches.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl03_rptSubMenu_ctl03_link"},
								{"innerText","My searches"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/PasswordReminder.aspx"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl03_rptSubMenu_ctl04_link"},
								{"innerText","Password Reminder"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Rss-Feeds.html"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl03_rptSubMenu_ctl05_link"},
								{"innerText","RSS Feeds"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href",""},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl04_link"},
								{"innerText","Recommended Links"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/AsiaHedge"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl04_rptSubMenu_ctl01_link"},
								{"innerText","AsiaHedge"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/EuroHedge"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl04_rptSubMenu_ctl02_link"},
								{"innerText","EuroHedge"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/InvestHedge"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl04_rptSubMenu_ctl03_link"},
								{"innerText","InvestHedge"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/UCITS"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl04_rptSubMenu_ctl04_link"},
								{"innerText","Absolute UCITS"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","http://www.hedgefundintelligence.com/AbsoluteReturn"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl04_rptSubMenu_ctl05_link"},
								{"innerText","Absolute Return"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Jobs.aspx"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl04_rptSubMenu_ctl06_link"},
								{"innerText","Industry Jobs"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","http://www.hedgefundintelligence.com/Stub.aspx?StubID=26228"},
								{"id","ctl00_mfFooter_bmMenu_rptMenu_ctl04_rptSubMenu_ctl07_link"},
								{"innerText","UCITS league tables"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","http://www.euromoneyplc.com"},
								{"innerText","Euromoney Institutional Investor PLC"}
							}
						}
					}
				};
			}
		}

	}
}
	
