// -----------------------------------------------------------------------
// <copyright file="FreeTrialZeroStep.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the FreeTrialZeroStep class
	/// </summary>
	public partial class FreeTrialZeroStep 
	{	
		public FreeTrialZeroStep(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets Next Button
		/// </summary> 
		private Button Next
		{
			get { return new Button("Next", "//input[@value='Next']", 0, false); }
		}

		/// <summary>
		/// Gets RegisterHereForAFreeTrial Label
		/// </summary> 
		private Label RegisterHereForAFreeTrial
		{
			get { return new Label("RegisterHereForAFreeTrial", "//h2[contains(text(),'Register here for your FREE 48 hour trial')]", 0, false); }
		}

	}
}
	
