// -----------------------------------------------------------------------
// <copyright file="FreeTrialStepOnePage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the FreeTrialStepOnePage class
	/// </summary>
	public partial class FreeTrialStepOnePage 
	{	
		public FreeTrialStepOnePage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets Header HeaderComponent
		/// </summary> 
		public HeaderComponent Header
		{
			get { return new HeaderComponent(); }
		}

		/// <summary>
		/// Gets TopMenu TopMenuComponent
		/// </summary> 
		public TopMenuComponent TopMenu
		{
			get { return new TopMenuComponent(); }
		}

		/// <summary>
		/// Gets EmailAddressTextbox Textbox
		/// </summary> 
		private Textbox EmailAddressTextbox
		{
			get { return new Textbox("EmailAddressTextbox", "//input[contains(@id,'EmailAddress')]", 0, false); }
		}

		/// <summary>
		/// Gets ConfirmEmailAddressTextbox Textbox
		/// </summary> 
		private Textbox ConfirmEmailAddressTextbox
		{
			get { return new Textbox("ConfirmEmailAddressTextbox", "//input[contains(@id,'EmailCompare')]", 0, false); }
		}

		/// <summary>
		/// Gets SubmitButton Button
		/// </summary> 
		private Button SubmitButton
		{
			get { return new Button("SubmitButton", "//input[contains(@id,'Button1')]", 0, false); }
		}

		/// <summary>
		/// Gets MissingEmailAddressValidationMessage Textbox
		/// </summary> 
		private Textbox MissingEmailAddressValidationMessage
		{
			get { return new Textbox("MissingEmailAddressValidationMessage", "//span[text()='You must enter an e-mail address']", 0, false); }
		}

		/// <summary>
		/// Gets MissingEmailAddressConfirmationValidationMessage Textbox
		/// </summary> 
		private Textbox MissingEmailAddressConfirmationValidationMessage
		{
			get { return new Textbox("MissingEmailAddressConfirmationValidationMessage", "//span[text()='You must confirm your e-mail address']", 0, false); }
		}

		/// <summary>
		/// Gets EmailAddressMustBeTheSameValidationMessage Textbox
		/// </summary> 
		private Textbox EmailAddressMustBeTheSameValidationMessage
		{
			get { return new Textbox("EmailAddressMustBeTheSameValidationMessage", "//span[text()='The email address must be the same']", 0, false); }
		}

		/// <summary>
		/// Gets FreeTrialStepOneSignUpStatus list
		/// </summary>
		public RequiredElements FreeTrialStepOneSignUpStatus
		{
			get
			{
				return new RequiredElements
				{
					Name = "FreeTrialStepOneSignUpStatus",
					Xpath = "//table[@class='FreeTrialProgressbar progressbar']",
					Filter = "td",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Select Products"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Email Address"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Your Details"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Confirmation"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets FreeTrialStepOneRegistrationPanel list
		/// </summary>
		public RequiredElements FreeTrialStepOneRegistrationPanel
		{
			get
			{
				return new RequiredElements
				{
					Name = "FreeTrialStepOneRegistrationPanel",
					Xpath = "//div[contains(@id,'pnlForm')]",
					Filter = "label|input",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "label",
							Type = "label",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Email address:"}
							}
						}, new Element
						{
							Name = "input",
							Type = "TextBox",
							Attributes = new Dictionary<string, string>
							{
								{"id","ctl00_phMain_ShowCheckoutControl_EmailContainer_EmailAddress"}
							}
						}, new Element
						{
							Name = "label",
							Type = "label",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Confirm email address:"}
							}
						}, new Element
						{
							Name = "input",
							Type = "TextBox",
							Attributes = new Dictionary<string, string>
							{
								{"id","ctl00_phMain_ShowCheckoutControl_EmailContainer_EmailCompare"}
							}
						}, new Element
						{
							Name = "input",
							Type = "Button",
							Attributes = new Dictionary<string, string>
							{
								{"value","Next"},
								{"id","ctl00_phMain_ShowCheckoutControl_EmailContainer_Button1"}
							}
						}
					}
				};
			}
		}

	}
}
	
