// -----------------------------------------------------------------------
// <copyright file="GTBTVPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the GTBTVPage class
	/// </summary>
	public partial class GTBTVPage 
	{	
		public GTBTVPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets GTBTV Label
		/// </summary> 
		private Label GTBTV
		{
			get { return new Label("GTBTV", "//h2//span[contains(text(), 'Video Archive')]", 0, false); }
		}

	}
}
	
