// -----------------------------------------------------------------------
// <copyright file="HeaderComponent.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the HeaderComponent class
	/// </summary>
	public partial class HeaderComponent 
	{	
		public HeaderComponent(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets MyAccountBox MyAccountBoxComponent
		/// </summary> 
		public MyAccountBoxComponent MyAccountBox
		{
			get { return new MyAccountBoxComponent(false); }
		}

		/// <summary>
		/// Gets Logo Image
		/// </summary> 
		private Image Logo
		{
			get { return new Image("Logo", "//img[@id='ctl00_mhHeader_zbHeader_ctl04_imgLogoHFI']", 3, false); }
		}

		/// <summary>
		/// Gets Login Link
		/// </summary> 
		private Link Login
		{
			get { return new Link("Login", "//a[@class='login']", 3, false); }
		}

		/// <summary>
		/// Gets SignUpForFree Link
		/// </summary> 
		private Link SignUpForFree
		{
			get { return new Link("SignUpForFree", "//li[contains(@id,'MenuItem')]//a[text()='Free Trial']", 3, false); }
		}

		/// <summary>
		/// Gets SearchTextbox Textbox
		/// </summary> 
		private Textbox SearchTextbox
		{
			get { return new Textbox("SearchTextbox", "//input[contains(@id, 'Keywords')]", 3, false); }
		}

		/// <summary>
		/// Gets SearchButton Button
		/// </summary> 
		private Button SearchButton
		{
			get { return new Button("SearchButton", "//input[contains(@id, 'Submit')]", 3, false); }
		}

		/// <summary>
		/// Gets MyEMAccount Button
		/// </summary> 
		private Button MyEMAccount
		{
			get { return new Button("MyEMAccount", "//a[text()='My Account']", 0, false); }
		}

		/// <summary>
		/// Gets Logout Button
		/// </summary> 
		private Button Logout
		{
			get { return new Button("Logout", "//a[text()='Log Out']|//a[text()='Logout']", 0, false); }
		}

		/// <summary>
		/// Gets GoogleTranslate Link
		/// </summary> 
		private Link GoogleTranslate
		{
			get { return new Link("GoogleTranslate", "//div[@id='google_translate_element']/a[@class='goog-te-menu-value']", 0, true); }
		}

		/// <summary>
		/// Gets ShoppingBasket Link
		/// </summary> 
		private Link ShoppingBasket
		{
			get { return new Link("ShoppingBasket", "//div[@class='navigation']//a[text()='Shopping Basket']", 0, true); }
		}

		/// <summary>
		/// Gets ContactUs Link
		/// </summary> 
		private Link ContactUs
		{
			get { return new Link("ContactUs", "//div[@class='navigation']//a[text()='Contact us']", 0, true); }
		}

		/// <summary>
		/// Gets SignUp Link
		/// </summary> 
		private Link SignUp
		{
			get { return new Link("SignUp", "//a[text()='Sign Up']", 0, false); }
		}

		/// <summary>
		/// Gets Subscribe Link
		/// </summary> 
		private Link Subscribe
		{
			get { return new Link("Subscribe", "//a[text()='Subscribe Now']", 0, false); }
		}

		/// <summary>
		/// Gets EuroHedge Link
		/// </summary> 
		private Link EuroHedge
		{
			get { return new Link("EuroHedge", "//div[@id='sites_nav']//a[@href = '/EuroHedge']", 0, false); }
		}

		/// <summary>
		/// Gets AsiaHedge Link
		/// </summary> 
		private Link AsiaHedge
		{
			get { return new Link("AsiaHedge", "//div[@id='sites_nav']//a[@href = '/AsiaHedge']", 0, false); }
		}

		/// <summary>
		/// Gets InvestHedge Link
		/// </summary> 
		private Link InvestHedge
		{
			get { return new Link("InvestHedge", "//div[@id='sites_nav']//a[@href = '/InvestHedge']", 0, false); }
		}

		/// <summary>
		/// Gets AbsoluteUcits Link
		/// </summary> 
		private Link AbsoluteUcits
		{
			get { return new Link("AbsoluteUcits", "//div[@id='sites_nav']//a[@href = '/UCITS']", 0, false); }
		}

		/// <summary>
		/// Gets AbsoluteReturn Link
		/// </summary> 
		private Link AbsoluteReturn
		{
			get { return new Link("AbsoluteReturn", "//div[@id='sites_nav']//a[@href = '/AbsoluteReturn']", 0, false); }
		}

	}
}
	
