// -----------------------------------------------------------------------
// <copyright file="InterviewsPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the InterviewsPage class
	/// </summary>
	public partial class InterviewsPage 
	{	
		public InterviewsPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets Interviews Label
		/// </summary> 
		private Label Interviews
		{
			get { return new Label("Interviews", "//h2[contains(text(), 'All interviews')]", 0, false); }
		}

	}
}
	
