// -----------------------------------------------------------------------
// <copyright file="LoginPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the LoginPage class
	/// </summary>
	public partial class LoginPage 
	{	
		public LoginPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets Username Textbox
		/// </summary> 
		public Textbox Username
		{
			get { return new Textbox("Username", "//div[@class='login']//input[contains(@id, 'Username')]", 0, false); }
		}

		/// <summary>
		/// Gets Password Textbox
		/// </summary> 
		private Textbox Password
		{
			get { return new Textbox("Password", "//div[@class='login']//input[contains(@id,'Password')]", 0, false); }
		}

		/// <summary>
		/// Gets Login Button
		/// </summary> 
		private Button Login
		{
			get { return new Button("Login", "//div[@class='login']//input[contains(@id,'Submit')]", 3, false); }
		}

		/// <summary>
		/// Gets RememberMe Checkbox
		/// </summary> 
		private Checkbox RememberMe
		{
			get { return new Checkbox("RememberMe", "//div[@class='login']//input[contains(@id,'RememberMe')]", 3, false); }
		}

		/// <summary>
		/// Gets Header HeaderComponent
		/// </summary> 
		public HeaderComponent Header
		{
			get { return new HeaderComponent(); }
		}

		/// <summary>
		/// Gets Footer FooterComponent
		/// </summary> 
		public FooterComponent Footer
		{
			get { return new FooterComponent(); }
		}

		/// <summary>
		/// Gets SidePanel SidePanelComponent
		/// </summary> 
		public SidePanelComponent SidePanel
		{
			get { return new SidePanelComponent(); }
		}

		/// <summary>
		/// Gets TopMenu TopMenuComponent
		/// </summary> 
		public TopMenuComponent TopMenu
		{
			get { return new TopMenuComponent(); }
		}

		/// <summary>
		/// Gets LoginPageRequiredElements list
		/// </summary>
		public RequiredElements LoginPageRequiredElements
		{
			get
			{
				return new RequiredElements
				{
					Name = "LoginPageRequiredElements",
					Xpath = "//div[@class='main_login']",
					Filter = "a|label|h2",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "h2",
							Type = "h2",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Already have an account?"}
							}
						}, new Element
						{
							Name = "h2",
							Type = "h2",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Subscribe"}
							}
						}, new Element
						{
							Name = "label",
							Type = "label",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Username:"}
							}
						}, new Element
						{
							Name = "label",
							Type = "label",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Password:"}
							}
						}, new Element
						{
							Name = "label",
							Type = "label",
							Attributes = new Dictionary<string, string>
							{
								{"id","ctl00_phMain_zbMiddle_ctl01_lblRemeberMe"},
								{"innerText","Remember me"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","javascript:{};"},
								{"innerText","Forgot password"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/SubscribeNow.html"},
								{"innerText","Subscribe now"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/FreeTrial.html"},
								{"innerText","Free Trial"}
							}
						}, new Element
						{
							Name = "h2",
							Type = "h2",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Free trial"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Registration.html"},
								{"id","ctl00_phMain_zbMiddle_ctl01_hlRegister"},
								{"innerText","Register"}
							}
						}
					}
				};
			}
		}

	}
}
	
