// -----------------------------------------------------------------------
// <copyright file="MyAccountPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the MyAccountPage class
	/// </summary>
	public partial class MyAccountPage 
	{	
		public MyAccountPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets MyAccountHeader Label
		/// </summary> 
		private Label MyAccountHeader
		{
			get { return new Label("MyAccountHeader", "//h1[text()='My Account']", 0, false); }
		}

		/// <summary>
		/// Gets UpdateDetails Button
		/// </summary> 
		private Button UpdateDetails
		{
			get { return new Button("UpdateDetails", "//a[text()='Update details']", 5, false); }
		}

		/// <summary>
		/// Gets ChangePassword Button
		/// </summary> 
		private Button ChangePassword
		{
			get { return new Button("ChangePassword", "//div[@class='highlight myaccount']//a[text()='Change password']", 0, false); }
		}

		/// <summary>
		/// Gets NewsletterPreferences Button
		/// </summary> 
		private Button NewsletterPreferences
		{
			get { return new Button("NewsletterPreferences", "//a[text()='Update newsletter preferences']", 0, false); }
		}

		/// <summary>
		/// Gets MyClippings Button
		/// </summary> 
		private Button MyClippings
		{
			get { return new Button("MyClippings", "//a[text()='Manage clippings']", 0, false); }
		}

		/// <summary>
		/// Gets ManageYourAddresses Link
		/// </summary> 
		public Link ManageYourAddresses
		{
			get { return new Link("ManageYourAddresses", "//a[text()='Manage Your Addresses']", 0, false); }
		}

		/// <summary>
		/// Gets ViewYourPreviousPurchases Link
		/// </summary> 
		public Link ViewYourPreviousPurchases
		{
			get { return new Link("ViewYourPreviousPurchases", "//a[text()='View Your Previous Purchases']", 0, false); }
		}

		/// <summary>
		/// Gets ViewYourSubscriptions Link
		/// </summary> 
		public Link ViewYourSubscriptions
		{
			get { return new Link("ViewYourSubscriptions", "//a[text()='View Your Subscriptions']", 0, false); }
		}

		/// <summary>
		/// Gets Header HeaderComponent
		/// </summary> 
		public HeaderComponent Header
		{
			get { return new HeaderComponent(); }
		}

		/// <summary>
		/// Gets Footer FooterComponent
		/// </summary> 
		public FooterComponent Footer
		{
			get { return new FooterComponent(); }
		}

		/// <summary>
		/// Gets SidePanel SidePanelComponent
		/// </summary> 
		public SidePanelComponent SidePanel
		{
			get { return new SidePanelComponent(); }
		}

		/// <summary>
		/// Gets TopMenu TopMenuComponent
		/// </summary> 
		public TopMenuComponent TopMenu
		{
			get { return new TopMenuComponent(); }
		}

		/// <summary>
		/// Gets Breadcrumb BreadcrumbComponent
		/// </summary> 
		public BreadcrumbComponent Breadcrumb
		{
			get { return new BreadcrumbComponent(); }
		}

		/// <summary>
		/// Gets MyAccountPageRequiredElements list
		/// </summary>
		public RequiredElements MyAccountPageRequiredElements
		{
			get
			{
				return new RequiredElements
				{
					Name = "MyAccountPageRequiredElements",
					Xpath = "//div[@class='col_default']",
					Filter = "h1|h2",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "h1",
							Type = "h1",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","My Account"}
							}
						}, new Element
						{
							Name = "h2",
							Type = "h2",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","My personal details"}
							}
						}, new Element
						{
							Name = "h2",
							Type = "h2",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","My e-newsletter preferences"}
							}
						}, new Element
						{
							Name = "h2",
							Type = "h2",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","My Clippings"}
							}
						}, new Element
						{
							Name = "h2",
							Type = "h2",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","My Saved Searches"}
							}
						}
					}
				};
			}
		}

	}
}
	
