// -----------------------------------------------------------------------
// <copyright file="MyEMAccountBoxComponent.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the MyEMAccountBoxComponent class
	/// </summary>
	public partial class MyEMAccountBoxComponent 
	{	
		public MyEMAccountBoxComponent(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets LoginInfo Label
		/// </summary> 
		private Label LoginInfo
		{
			get { return new Label("LoginInfo", "//span[@class='login_info']", 0, false); }
		}

		/// <summary>
		/// Gets MyDetails Link
		/// </summary> 
		private Link MyDetails
		{
			get { return new Link("MyDetails", "//div[@class='user-menu-content']//a[text()='My Details']", 0, false); }
		}

		/// <summary>
		/// Gets MyInterests Link
		/// </summary> 
		private Link MyInterests
		{
			get { return new Link("MyInterests", "//div[@class='user-menu-content']//a[text()='My Interests']", 0, false); }
		}

		/// <summary>
		/// Gets MyEvents Link
		/// </summary> 
		private Link MyEvents
		{
			get { return new Link("MyEvents", "//div[@class='user-menu-content']//a[text()='My Events']", 0, false); }
		}

		/// <summary>
		/// Gets ChangePassword Link
		/// </summary> 
		private Link ChangePassword
		{
			get { return new Link("ChangePassword", "//div[@class='user-menu-content']//a[text()='Change Password']", 0, false); }
		}

		/// <summary>
		/// Gets Logout Button
		/// </summary> 
		private Button Logout
		{
			get { return new Button("Logout", "//div[@class='user-menu-content']//input[@value='Logout']", 0, false); }
		}

		/// <summary>
		/// Gets Close Button
		/// </summary> 
		private Button Close
		{
			get { return new Button("Close", "//div[@class='user-menu']//input[@value='Close']", 0, false); }
		}

		/// <summary>
		/// Gets MyEMAccountBoxUniqueElement Button
		/// </summary> 
		private Button MyEMAccountBoxUniqueElement
		{
			get { return new Button("MyEMAccountBoxUniqueElement", "//input[@value='Close']", 0, false); }
		}

	}
}
	
