// -----------------------------------------------------------------------
// <copyright file="NewsletterPreferencesComponent.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the NewsletterPreferencesComponent class
	/// </summary>
	public partial class NewsletterPreferencesComponent 
	{	
		public NewsletterPreferencesComponent(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets EMNewsAlerts Checkbox
		/// </summary> 
		private Checkbox EMNewsAlerts
		{
			get { return new Checkbox("EMNewsAlerts", "//input[contains(@name, 'NewsletterList')]", 0, false); }
		}

		/// <summary>
		/// Gets PEMonthlyMagazineUpdate Checkbox
		/// </summary> 
		public Checkbox PEMonthlyMagazineUpdate
		{
			get { return new Checkbox("PEMonthlyMagazineUpdate", "//tr[td[text()='Petroleum Economist - Monthly Magazine Update']]//input", 5, false); }
		}

		/// <summary>
		/// Gets PEBreakingNews Checkbox
		/// </summary> 
		public Checkbox PEBreakingNews
		{
			get { return new Checkbox("PEBreakingNews", "//tr[td[text()='Petroleum Economist - Breaking News']]//input", 5, false); }
		}

		/// <summary>
		/// Gets PEBlogEmail Checkbox
		/// </summary> 
		public Checkbox PEBlogEmail
		{
			get { return new Checkbox("PEBlogEmail", "//tr[td[text()='Petroleum Economist - Blog Email']]//input", 5, false); }
		}

		/// <summary>
		/// Gets Html Radio
		/// </summary> 
		private Radio Html
		{
			get { return new Radio("Html", "//input[@id=//label[text()='HTML']/@for]", 0, false); }
		}

		/// <summary>
		/// Gets Text Radio
		/// </summary> 
		private Radio Text
		{
			get { return new Radio("Text", "//input[@id=//label[text()='Text']/@for]", 0, false); }
		}

	}
}
	
