// -----------------------------------------------------------------------
// <copyright file="NewsletterPreferencesPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the NewsletterPreferencesPage class
	/// </summary>
	public partial class NewsletterPreferencesPage 
	{	
		public NewsletterPreferencesPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets NewsletterPreferencesHeader Label
		/// </summary> 
		private Label NewsletterPreferencesHeader
		{
			get { return new Label("NewsletterPreferencesHeader", "//h1[text()='Email Newsletter Settings']", 0, false); }
		}

		/// <summary>
		/// Gets Submit Button
		/// </summary> 
		private Button Submit
		{
			get { return new Button("Submit", "//input[@value='Update']", 0, false); }
		}

		/// <summary>
		/// Gets UpdatedSettingsConfirmation Label
		/// </summary> 
		private Label UpdatedSettingsConfirmation
		{
			get { return new Label("UpdatedSettingsConfirmation", "//span[text()='Your Email Newsletter Settings have been updated']", 0, false); }
		}

		/// <summary>
		/// Gets Header HeaderComponent
		/// </summary> 
		public HeaderComponent Header
		{
			get { return new HeaderComponent(); }
		}

		/// <summary>
		/// Gets Footer FooterComponent
		/// </summary> 
		public FooterComponent Footer
		{
			get { return new FooterComponent(); }
		}

		/// <summary>
		/// Gets SidePanel SidePanelComponent
		/// </summary> 
		public SidePanelComponent SidePanel
		{
			get { return new SidePanelComponent(); }
		}

		/// <summary>
		/// Gets TopMenu TopMenuComponent
		/// </summary> 
		public TopMenuComponent TopMenu
		{
			get { return new TopMenuComponent(); }
		}

		/// <summary>
		/// Gets Breadcrumb BreadcrumbComponent
		/// </summary> 
		public BreadcrumbComponent Breadcrumb
		{
			get { return new BreadcrumbComponent(); }
		}

		/// <summary>
		/// Gets NewsletterPreferences NewsletterPreferencesComponent
		/// </summary> 
		public NewsletterPreferencesComponent NewsletterPreferences
		{
			get { return new NewsletterPreferencesComponent(); }
		}

		/// <summary>
		/// Gets NewsletterPreferencesRequiredElements list
		/// </summary>
		public RequiredElements NewsletterPreferencesRequiredElements
		{
			get
			{
				return new RequiredElements
				{
					Name = "NewsletterPreferencesRequiredElements",
					Xpath = "//div[@class='col_default normal']",
					Filter = "h1|td",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "h1",
							Type = "h1",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Email Newsletter Settings"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","HFI Insight Monthly Email"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","AsiaHedge Weekly News"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","EuroHedge Weekly News"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","InvestHedge Weekly News"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","UCITS Weekly News"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Absolute Return Weekly Email"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","AsiaHedge Latest Issue Alert"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","EuroHedge Latest Issue Alert"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","InvestHedge Latest Issue Alert"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","AsiaHedge Newsflash"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","EuroHedge Newsflash"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","InvestHedge Newsflash"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","UCITS Newsflash"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Absolute Return Breaking News Email"}
							}
						}, new Element
						{
							Name = "td",
							Type = "td",
							Attributes = new Dictionary<string, string>
							{
								
							}
						}
					}
				};
			}
		}

	}
}
	
