// -----------------------------------------------------------------------
// <copyright file="PaymentPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the PaymentPage class
	/// </summary>
	public partial class PaymentPage 
	{	
		public PaymentPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets CardType Dropdown
		/// </summary> 
		private Dropdown CardType
		{
			get { return new Dropdown("CardType", "//select[@id='card_type']", 0, false); }
		}

		/// <summary>
		/// Gets CardNumber Textbox
		/// </summary> 
		private Textbox CardNumber
		{
			get { return new Textbox("CardNumber", "//input[@id='card_number']", 0, false); }
		}

		/// <summary>
		/// Gets CardCVN Textbox
		/// </summary> 
		private Textbox CardCVN
		{
			get { return new Textbox("CardCVN", "//input[@id='card_cvn']", 0, false); }
		}

		/// <summary>
		/// Gets CardExpirationYear Dropdown
		/// </summary> 
		private Dropdown CardExpirationYear
		{
			get { return new Dropdown("CardExpirationYear", "//select[@id='card_expiry_year']", 0, false); }
		}

		/// <summary>
		/// Gets Pay Button
		/// </summary> 
		private Button Pay
		{
			get { return new Button("Pay", "//input[@value='Pay']", 0, false); }
		}

		/// <summary>
		/// Gets Quantity Label
		/// </summary> 
		private Label Quantity
		{
			get { return new Label("Quantity", "//td[@class='col-qty']", 5, false); }
		}

	}
}
	
