// -----------------------------------------------------------------------
// <copyright file="RegistrationDetailsPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the RegistrationDetailsPage class
	/// </summary>
	public partial class RegistrationDetailsPage 
	{	
		public RegistrationDetailsPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets Header HeaderComponent
		/// </summary> 
		public HeaderComponent Header
		{
			get { return new HeaderComponent(); }
		}

		/// <summary>
		/// Gets NewsletterPreferences NewsletterPreferencesComponent
		/// </summary> 
		public NewsletterPreferencesComponent NewsletterPreferences
		{
			get { return new NewsletterPreferencesComponent(); }
		}

		/// <summary>
		/// Gets PageTitle Label
		/// </summary> 
		private Label PageTitle
		{
			get { return new Label("PageTitle", "//h1[text()='Registration details']", 0, false); }
		}

		/// <summary>
		/// Gets Title Dropdown
		/// </summary> 
		private Dropdown Title
		{
			get { return new Dropdown("Title", "//select[contains(@id, 'Title')]", 0, false); }
		}

		/// <summary>
		/// Gets FirstName Textbox
		/// </summary> 
		private Textbox FirstName
		{
			get { return new Textbox("FirstName", "//input[contains(@id, 'FirstName')]", 0, false); }
		}

		/// <summary>
		/// Gets LastName Textbox
		/// </summary> 
		private Textbox LastName
		{
			get { return new Textbox("LastName", "//input[contains(@id, 'LastName')]", 0, false); }
		}

		/// <summary>
		/// Gets CompanyName Textbox
		/// </summary> 
		private Textbox CompanyName
		{
			get { return new Textbox("CompanyName", "//input[contains(@id, 'CompanyName')]", 0, false); }
		}

		/// <summary>
		/// Gets AddressLineOne Textbox
		/// </summary> 
		private Textbox AddressLineOne
		{
			get { return new Textbox("AddressLineOne", "//input[contains(@id, 'Address1')]", 0, false); }
		}

		/// <summary>
		/// Gets AddressLineTwo Textbox
		/// </summary> 
		private Textbox AddressLineTwo
		{
			get { return new Textbox("AddressLineTwo", "//input[contains(@id, 'Address2')]", 0, false); }
		}

		/// <summary>
		/// Gets AddressLineThree Textbox
		/// </summary> 
		private Textbox AddressLineThree
		{
			get { return new Textbox("AddressLineThree", "//input[contains(@id, 'Address3')]", 0, false); }
		}

		/// <summary>
		/// Gets City Textbox
		/// </summary> 
		private Textbox City
		{
			get { return new Textbox("City", "//input[contains(@id, 'City')]", 0, false); }
		}

		/// <summary>
		/// Gets State Dropdown
		/// </summary> 
		private Dropdown State
		{
			get { return new Dropdown("State", "//select[contains(@id, 'State')]", 0, false); }
		}

		/// <summary>
		/// Gets County Textbox
		/// </summary> 
		private Textbox County
		{
			get { return new Textbox("County", "//input[contains(@id, 'County')]", 0, false); }
		}

		/// <summary>
		/// Gets PostCode Textbox
		/// </summary> 
		private Textbox PostCode
		{
			get { return new Textbox("PostCode", "//input[contains(@id, 'Postcode')]", 0, false); }
		}

		/// <summary>
		/// Gets Country Dropdown
		/// </summary> 
		private Dropdown Country
		{
			get { return new Dropdown("Country", "//select[contains(@id, 'Country')]", 0, false); }
		}

		/// <summary>
		/// Gets Telephone Textbox
		/// </summary> 
		private Textbox Telephone
		{
			get { return new Textbox("Telephone", "//input[contains(@id, 'TelephoneNumber')]", 0, false); }
		}

		/// <summary>
		/// Gets Fax Textbox
		/// </summary> 
		private Textbox Fax
		{
			get { return new Textbox("Fax", "//input[contains(@id, 'Fax')]", 0, false); }
		}

		/// <summary>
		/// Gets Update Button
		/// </summary> 
		private Button Update
		{
			get { return new Button("Update", "//div[@class='termsandconditions']//input[contains(@id, 'btnSubmit')]", 0, false); }
		}

		/// <summary>
		/// Gets AccountUpdatedSuccessfully Label
		/// </summary> 
		private Label AccountUpdatedSuccessfully
		{
			get { return new Label("AccountUpdatedSuccessfully", "//*[contains(text(), 'Your account details have been updated.')]", 0, false); }
		}

		/// <summary>
		/// Gets TelephoneChoice Checkbox
		/// </summary> 
		public Checkbox TelephoneChoice
		{
			get { return new Checkbox("TelephoneChoice", "//input[@id=//label[text()='Telephone']/@for]", 0, true); }
		}

		/// <summary>
		/// Gets FaxChoice Checkbox
		/// </summary> 
		public Checkbox FaxChoice
		{
			get { return new Checkbox("FaxChoice", "//input[@id=//label[text()='Fax']/@for]", 0, true); }
		}

		/// <summary>
		/// Gets EmailChoice Checkbox
		/// </summary> 
		public Checkbox EmailChoice
		{
			get { return new Checkbox("EmailChoice", "//input[@id=//label[text()='Email']/@for]", 0, true); }
		}

		/// <summary>
		/// Gets MailChoice Checkbox
		/// </summary> 
		public Checkbox MailChoice
		{
			get { return new Checkbox("MailChoice", "//input[@id=//label[text()='Mail']/@for]", 0, true); }
		}

		/// <summary>
		/// Gets OffersFromOtherCompaniesChoice Checkbox
		/// </summary> 
		public Checkbox OffersFromOtherCompaniesChoice
		{
			get { return new Checkbox("OffersFromOtherCompaniesChoice", "//input[contains(@id, 'bythird') and @type='checkbox']", 0, true); }
		}

		/// <summary>
		/// Gets PrivacyPolicy Checkbox
		/// </summary> 
		private Checkbox PrivacyPolicy
		{
			get { return new Checkbox("PrivacyPolicy", "//input[contains(@id, 'privacypolicy') and @type='checkbox']", 0, true); }
		}

		/// <summary>
		/// Gets TermsAndConditions Checkbox
		/// </summary> 
		private Checkbox TermsAndConditions
		{
			get { return new Checkbox("TermsAndConditions", "//input[contains(@id, 'TermsAndConditions') and @type='checkbox']", 0, false); }
		}

		/// <summary>
		/// Gets RegistrationDetailsPageRequiredElements list
		/// </summary>
		public RequiredElements RegistrationDetailsPageRequiredElements
		{
			get
			{
				return new RequiredElements
				{
					Name = "RegistrationDetailsPageRequiredElements",
					Xpath = "//div[@class='checkout']",
					Filter = "h2",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "h2",
							Type = "h2",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Your details"}
							}
						}, new Element
						{
							Name = "h2",
							Type = "h2",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Address"}
							}
						}, new Element
						{
							Name = "h2",
							Type = "h2",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Email newsletter preferences"}
							}
						}, new Element
						{
							Name = "h2",
							Type = "h2",
							Attributes = new Dictionary<string, string>
							{
								{"innerText","Data protection"}
							}
						}
					}
				};
			}
		}

	}
}
	
