// -----------------------------------------------------------------------
// <copyright file="SubscribtionZeroPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the SubscribtionZeroPage class
	/// </summary>
	public partial class SubscribtionZeroPage 
	{	
		public SubscribtionZeroPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets EuroHedge Link
		/// </summary> 
		private Link EuroHedge
		{
			get { return new Link("EuroHedge", "//a[contains(@href,'EuroHedge-SubscribeNow.html')]", 0, false); }
		}

		/// <summary>
		/// Gets AsiaHedge Link
		/// </summary> 
		private Link AsiaHedge
		{
			get { return new Link("AsiaHedge", "//a[contains(@href,'AsiaHedge-SubscribeNow.html')]", 0, false); }
		}

		/// <summary>
		/// Gets InvestHedge Link
		/// </summary> 
		private Link InvestHedge
		{
			get { return new Link("InvestHedge", "//a[contains(@href,'InvestHedge-SubscribeNow.html')]", 0, false); }
		}

		/// <summary>
		/// Gets AU Link
		/// </summary> 
		private Link AU
		{
			get { return new Link("AU", "//a[contains(@href,'Absolute-UCITS-SubscribeNow.html')]", 0, false); }
		}

		/// <summary>
		/// Gets AR Link
		/// </summary> 
		private Link AR
		{
			get { return new Link("AR", "//a[contains(@href,'/AbsoluteReturn-SubscribeNow.html?ls=Main_Sub_pg')]", 0, false); }
		}

	}
}
	
