// -----------------------------------------------------------------------
// <copyright file="TopMenuComponent.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the TopMenuComponent class
	/// </summary>
	public partial class TopMenuComponent 
	{	
		public TopMenuComponent(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets Home Link
		/// </summary> 
		private Link Home
		{
			get { return new Link("Home", "//div[@class='nav_bar']//a[text()='Home']", 0, true); }
		}

		/// <summary>
		/// Gets Sectors Link
		/// </summary> 
		private Link Sectors
		{
			get { return new Link("Sectors", "//div[@class='nav_bar']//a[@title='Sectors']", 0, true); }
		}

		/// <summary>
		/// Gets Interviews Link
		/// </summary> 
		private Link Interviews
		{
			get { return new Link("Interviews", "//div[@class='nav_bar']//a[@title='Interviews']", 0, true); }
		}

		/// <summary>
		/// Gets CFOs Link
		/// </summary> 
		private Link CFOs
		{
			get { return new Link("CFOs", "//div[@class='nav_bar']//a[@title='GTB-CFO']", 0, true); }
		}

		/// <summary>
		/// Gets CMOs Link
		/// </summary> 
		private Link CMOs
		{
			get { return new Link("CMOs", "//div[@class='nav_bar']//a[@title='GTB-CMO']", 0, true); }
		}

		/// <summary>
		/// Gets GTBTV Link
		/// </summary> 
		private Link GTBTV
		{
			get { return new Link("GTBTV", "//a[text()='GTB TV']", 0, true); }
		}

		/// <summary>
		/// Gets AboutUs Link
		/// </summary> 
		private Link AboutUs
		{
			get { return new Link("AboutUs", "//div[@class='nav_bar']//a[@title='AboutUs']", 0, true); }
		}

		/// <summary>
		/// Gets MyAccount Link
		/// </summary> 
		private Link MyAccount
		{
			get { return new Link("MyAccount", "//div[@class='nav_bar']//a[@title='MyAccount']", 0, true); }
		}

		/// <summary>
		/// Gets News Link
		/// </summary> 
		private Link News
		{
			get { return new Link("News", "//div[@id='nav']//a[text()='News']", 0, false); }
		}

		/// <summary>
		/// Gets EventsH Link
		/// </summary> 
		private Link EventsH
		{
			get { return new Link("EventsH", "//div[@id='nav']//a[text()='Events']", 0, true); }
		}

		/// <summary>
		/// Gets Research Link
		/// </summary> 
		private Link Research
		{
			get { return new Link("Research", "//div[@id='nav']//a[text()='Research & Rankings']", 0, true); }
		}

		/// <summary>
		/// Gets Opinion Link
		/// </summary> 
		private Link Opinion
		{
			get { return new Link("Opinion", "//div[@id='nav']//a[text()='Opinion']", 0, true); }
		}

		/// <summary>
		/// Gets Investors Link
		/// </summary> 
		private Link Investors
		{
			get { return new Link("Investors", "//div[@id='nav']//a[text()='Investors']", 0, true); }
		}

		/// <summary>
		/// Gets Performance Link
		/// </summary> 
		private Link Performance
		{
			get { return new Link("Performance", "//div[@id='nav']//a[text()='Performance']", 0, true); }
		}

		/// <summary>
		/// Gets Live Link
		/// </summary> 
		private Link Live
		{
			get { return new Link("Live", "//div[@id='nav']//a[text()='Live League Tables']", 0, true); }
		}

		/// <summary>
		/// Gets Database Link
		/// </summary> 
		private Link Database
		{
			get { return new Link("Database", "//div[@id='nav']//a[text()='Database']", 0, true); }
		}

		/// <summary>
		/// Gets EMView Link
		/// </summary> 
		private Link EMView
		{
			get { return new Link("EMView", "//div[@id='top_nav']//a[span[text()='EM View']]", 0, true); }
		}

		/// <summary>
		/// Gets Analysis Link
		/// </summary> 
		private Link Analysis
		{
			get { return new Link("Analysis", "//div[@id='top_nav']//a[span[text()='Analysis']]", 0, true); }
		}

		/// <summary>
		/// Gets CommentsAndOpinions Link
		/// </summary> 
		private Link CommentsAndOpinions
		{
			get { return new Link("CommentsAndOpinions", "//div[@id='top_nav']//a[text()='Comment & Opinion']", 0, true); }
		}

		/// <summary>
		/// Gets Features Link
		/// </summary> 
		private Link Features
		{
			get { return new Link("Features", "//div[@id='top_nav']//a[text()='Features']", 0, true); }
		}

		/// <summary>
		/// Gets Regions Link
		/// </summary> 
		private Link Regions
		{
			get { return new Link("Regions", "//div[@id='top_nav']//a[span[text()='Regions']]", 0, true); }
		}

		/// <summary>
		/// Gets Americas Link
		/// </summary> 
		private Link Americas
		{
			get { return new Link("Americas", "//div[@id='top_nav']//a[text()='Americas']", 0, true); }
		}

		/// <summary>
		/// Gets Asia Link
		/// </summary> 
		private Link Asia
		{
			get { return new Link("Asia", "//div[@id='top_nav']//a[text()='Asia']", 0, true); }
		}

		/// <summary>
		/// Gets EmergingEurope Link
		/// </summary> 
		private Link EmergingEurope
		{
			get { return new Link("EmergingEurope", "//div[@id='top_nav']//a[text()='Emerging Europe']", 0, true); }
		}

		/// <summary>
		/// Gets Global Link
		/// </summary> 
		private Link Global
		{
			get { return new Link("Global", "//div[@id='top_nav']//a[text()='Global']", 0, true); }
		}

		/// <summary>
		/// Gets MiddleEastAndAfrica Link
		/// </summary> 
		private Link MiddleEastAndAfrica
		{
			get { return new Link("MiddleEastAndAfrica", "//div[@id='top_nav']//a[text()='Middle East & Africa']", 0, true); }
		}

		/// <summary>
		/// Gets EconomicsAndPolicy Link
		/// </summary> 
		private Link EconomicsAndPolicy
		{
			get { return new Link("EconomicsAndPolicy", "//div[@id='top_nav']//a[span[text()='Economics & Policy']]", 0, true); }
		}

		/// <summary>
		/// Gets FinancialMarkets Link
		/// </summary> 
		private Link FinancialMarkets
		{
			get { return new Link("FinancialMarkets", "//div[@id='top_nav']//a[span[text()='Financial Markets']]", 0, true); }
		}

		/// <summary>
		/// Gets Development Link
		/// </summary> 
		private Link Development
		{
			get { return new Link("Development", "//div[@id='top_nav']//a[span[text()='Development']]", 0, true); }
		}

		/// <summary>
		/// Gets PollsAndAwards Link
		/// </summary> 
		private Link PollsAndAwards
		{
			get { return new Link("PollsAndAwards", "//div[@id='top_nav']//a[span[text()='Polls & Awards']]", 0, true); }
		}

		/// <summary>
		/// Gets Events Link
		/// </summary> 
		private Link Events
		{
			get { return new Link("Events", "//ul[@id='top_nav']//a[@href='/Forthcoming-Events.html']", 0, true); }
		}

		/// <summary>
		/// Gets Video Link
		/// </summary> 
		private Link Video
		{
			get { return new Link("Video", "//div[@id='top_nav']//a[span[text()='Video']]", 0, true); }
		}

		/// <summary>
		/// Gets TopMenuDefaultComponentRequiredElements list
		/// </summary>
		public RequiredElements TopMenuDefaultComponentRequiredElements
		{
			get
			{
				return new RequiredElements
				{
					Name = "TopMenuDefaultComponentRequiredElements",
					Xpath = "//ul[@id='top_nav']",
					Filter = "a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","http://data.hedgefundintelligence.com/funds4/database/255/default.aspx"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl01_link"},
								{"innerText","Database"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl02_link"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/News.html"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl03_link"},
								{"innerText","News"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Industry-Analysis.html"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl04_link"},
								{"innerText","Research & Rankings"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Blogs.html"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl05_link"},
								{"innerText","Opinion"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Forthcoming-Events.html"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl06_link"},
								{"innerText","Events"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Investors.html"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl07_link"},
								{"innerText","Investors"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Performance.html"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl08_link"},
								{"innerText","Performance"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/HFILiveLeagueTables.html"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl09_link"},
								{"innerText","Live League Tables"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","https://www.facebook.com/hedgefundintel"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl10_Hyperlink1"},
								{"innerText","facebook"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","http://www.linkedin.com/groups?mostPopular=&gid=3514"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl10_hypLinkedIn"},
								{"innerText","linked in"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","https://twitter.com/HedgeFundIntel"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl10_hypTwitter"},
								{"innerText","twitter"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets TopMenuAboutUsComponentRequiredElements list
		/// </summary>
		public RequiredElements TopMenuAboutUsComponentRequiredElements
		{
			get
			{
				return new RequiredElements
				{
					Name = "TopMenuAboutUsComponentRequiredElements",
					Xpath = "//ul[@id='top_nav']",
					Filter = "a",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","http://data.hedgefundintelligence.com/funds4/database/255/default.aspx"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl01_link"},
								{"innerText","Database"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl02_link"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/News.html"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl03_link"},
								{"innerText","News"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Industry-Analysis.html"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl04_link"},
								{"innerText","Research & Rankings"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Blogs.html"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl05_link"},
								{"innerText","Opinion"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Forthcoming-Events.html"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl06_link"},
								{"innerText","Events"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Investors.html"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl07_link"},
								{"innerText","Investors"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/Performance.html"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl08_link"},
								{"innerText","Performance"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","/HFILiveLeagueTables.html"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl09_link"},
								{"innerText","Live League Tables"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","https://www.facebook.com/hedgefundintel"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl10_Hyperlink1"},
								{"innerText","facebook"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","http://www.linkedin.com/groups?mostPopular=&gid=3514"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl10_hypLinkedIn"},
								{"innerText","linked in"}
							}
						}, new Element
						{
							Name = "a",
							Type = "Link",
							Attributes = new Dictionary<string, string>
							{
								{"href","https://twitter.com/HedgeFundIntel"},
								{"id","ctl00_mhHeader_tmTopMenu_rptMenu_ctl10_hypTwitter"},
								{"innerText","twitter"}
							}
						}
					}
				};
			}
		}

		/// <summary>
		/// Gets TopMenuEventsComponentRequiredElements list
		/// </summary>
		public RequiredElements TopMenuEventsComponentRequiredElements
		{
			get
			{
				return new RequiredElements
				{
					Name = "TopMenuEventsComponentRequiredElements",
					Xpath = "",
					Filter = "a",
					Optional = false,
					List = new List<Element>
					{
						
					}
				};
			}
		}

		/// <summary>
		/// Gets SignUpTopMenuComponentRequiredElements list
		/// </summary>
		public RequiredElements SignUpTopMenuComponentRequiredElements
		{
			get
			{
				return new RequiredElements
				{
					Name = "SignUpTopMenuComponentRequiredElements",
					Xpath = "",
					Filter = "a",
					Optional = false,
					List = new List<Element>
					{
						
					}
				};
			}
		}

		/// <summary>
		/// Gets TopMenuCookiesComponentRequiredElements list
		/// </summary>
		public RequiredElements TopMenuCookiesComponentRequiredElements
		{
			get
			{
				return new RequiredElements
				{
					Name = "TopMenuCookiesComponentRequiredElements",
					Xpath = "",
					Filter = "",
					Optional = false,
					List = new List<Element>
					{
						
					}
				};
			}
		}

	}
}
	
