// -----------------------------------------------------------------------
// <copyright file="VideoPage.cs" company="Euromoney">
// TODO: Update copyright text.
// </copyright>
// <auto-generated />
// -----------------------------------------------------------------------
namespace PageObjects.PageObjects
{
	using System.Collections.Generic;
	using System.Globalization;
	using Core;
	using Core.Controls;
	using Core.Configuration;
	using ConfigManager;

	/// <summary> 
	/// Initializes a new instance of the VideoPage class
	/// </summary>
	public partial class VideoPage 
	{	
		public VideoPage(bool optional=false)
		{
			this.Optional = optional;
		}


		/// <summary>
		/// Gets Header HeaderComponent
		/// </summary> 
		public HeaderComponent Header
		{
			get { return new HeaderComponent(); }
		}

		/// <summary>
		/// Gets Footer FooterComponent
		/// </summary> 
		public FooterComponent Footer
		{
			get { return new FooterComponent(); }
		}

		/// <summary>
		/// Gets SidePanel SidePanelComponent
		/// </summary> 
		public SidePanelComponent SidePanel
		{
			get { return new SidePanelComponent(); }
		}

		/// <summary>
		/// Gets TopMenu TopMenuComponent
		/// </summary> 
		public TopMenuComponent TopMenu
		{
			get { return new TopMenuComponent(); }
		}

		/// <summary>
		/// Gets Breadcrumb BreadcrumbComponent
		/// </summary> 
		public BreadcrumbComponent Breadcrumb
		{
			get { return new BreadcrumbComponent(); }
		}

		/// <summary>
		/// Gets VideoPageRequiredElements list
		/// </summary>
		public RequiredElements VideoPageRequiredElements
		{
			get
			{
				return new RequiredElements
				{
					Name = "VideoPageRequiredElements",
					Xpath = "//div",
					Filter = "object",
					Optional = false,
					List = new List<Element>
					{
						new Element
						{
							Name = "object",
							Type = "object",
							Attributes = new Dictionary<string, string>
							{
								{"id","myExperience"}
							}
						}
					}
				};
			}
		}

	}
}
	
